import { StyleSheet } from 'react-native';
import type { Palette } from '@/hooks/useThemedStyles';
import { platformShadow } from '@/lib/platformShadow';

export function createStyles(palette: Palette) {
  const isLight = palette.isLight;
  const {
    gameRoom: {
      raisedBackground,
      border: borderColor,
      surfaceShadow,
      heroBackground,
      heroGlowPrimary,
      heroGlowSecondary,
      topBarSurface,
      topBarBorder,
      heroBadgeBackground,
      heroBadgeBorder,
      heroBadgeIcon: heroBadgeIconColor,
      heroBadgeText: heroBadgeTextColor,
      actionBackground,
      actionBorder,
      statusLobby,
      statusInProgress,
      statusCompleted,
      leaveBackground,
      leaveDisabledBackground,
      leaveTint,
      deleteBackground,
      deleteDisabledBackground,
      deleteTint,
      errorBackground,
      errorBorder,
      errorText,
      backgroundGradient,
      backgroundGlow,
      decorPlay,
      decorCheck,
      decorAlert,
      titleBackground,
      titleBorder,
      titleGlow,
      titleText,
    },
  } = palette;
  const fill = StyleSheet.absoluteFillObject;
  return StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: palette.background,
      position: 'relative',
    },
    fullscreenContainer: {
      flex: 1,
      backgroundColor: palette.background,
      position: 'relative',
    },
    content: {
      padding: 24,
      gap: 20,
      paddingBottom: 48,
    },
    refreshTint: {
      color: palette.tint,
    },
    backgroundDecor: {
      ...fill,
      zIndex: 0,
    },
    backgroundGradientLayer: {
      ...fill,
      opacity: isLight ? 0.9 : 0.75,
    },
    backgroundGlowLayer: {
      position: 'absolute',
      top: -120,
      right: -80,
      width: 280,
      height: 280,
      borderRadius: 160,
      backgroundColor: backgroundGlow,
    },
    backgroundSparkTop: {
      position: 'absolute',
      top: 140,
      left: -40,
      width: 220,
      height: 220,
      borderRadius: 160,
      backgroundColor: `${decorPlay}1a`,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: `${decorPlay}4d`,
      transform: [{ rotate: '-22deg' }],
    },
    backgroundSparkBottom: {
      position: 'absolute',
      bottom: -80,
      right: -60,
      width: 240,
      height: 240,
      borderRadius: 160,
      backgroundColor: `${decorCheck}12`,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: `${decorCheck}4d`,
      transform: [{ rotate: '18deg' }],
    },
    backgroundGradientSwatchA: {
      backgroundColor: backgroundGradient[0],
    },
    backgroundGradientSwatchB: {
      backgroundColor: backgroundGradient[1],
    },
    backgroundGradientSwatchC: {
      backgroundColor: backgroundGradient[2],
    },
    topBar: {
      width: '100%',
      paddingHorizontal: 24,
      paddingTop: 4,
      paddingBottom: 4,
    },
    fullscreenTopBar: {
      paddingTop: 24,
      paddingHorizontal: 24,
      paddingBottom: 16,
      borderBottomWidth: StyleSheet.hairlineWidth,
      borderBottomColor: borderColor,
    },
    topBarCard: {
      width: '100%',
      backgroundColor: topBarSurface,
      borderRadius: 24,
      padding: 16,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: topBarBorder,
      gap: 16,
      ...platformShadow({
        color: surfaceShadow,
        opacity: isLight ? 0.9 : 0.7,
        radius: 14,
        offset: { width: 0, height: 6 },
        elevation: 3,
      }),
    },
    topBarCardCollapsed: {
      gap: 12,
      paddingBottom: 12,
    },
    topBarHeaderRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: 12,
      flexWrap: 'nowrap',
    },
    topBarTitleRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
      flexGrow: 1,
      flexShrink: 1,
      minWidth: 0,
      flexWrap: 'wrap',
    },
    topBarTitleIcon: {
      color: palette.tint,
    },
    topBarTitle: {
      color: palette.icon,
      fontSize: 13,
      lineHeight: 18,
      fontWeight: '600',
    },
    topBarSubtitle: {
      color: palette.icon,
      fontSize: 12,
      lineHeight: 16,
      marginTop: 2,
      flexShrink: 1,
      maxWidth: '100%',
    },
    controlsToggleButton: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
      paddingHorizontal: 10,
      paddingVertical: 6,
      borderRadius: 999,
      backgroundColor: actionBackground,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: actionBorder,
      flexShrink: 0,
      marginLeft: 'auto',
      ...platformShadow({
        color: surfaceShadow,
        opacity: isLight ? 0.35 : 0.55,
        radius: 8,
        offset: { width: 0, height: 3 },
        elevation: 2,
      }),
    },
    controlsToggleIcon: {
      color: palette.tint,
    },
    controlsToggleText: {
      color: palette.tint,
      fontSize: 12,
      fontWeight: '600',
    },
    fullscreenTableWrapper: {
      flex: 1,
    },
    actionGroup: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      alignItems: 'center',
      justifyContent: 'flex-start',
      gap: 10,
      alignSelf: 'stretch',
      marginTop: 4,
    },
    gameButton: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
      paddingHorizontal: 14,
      paddingVertical: 10,
      borderRadius: 999,
      backgroundColor: actionBackground,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: actionBorder,
      ...platformShadow({
        color: surfaceShadow,
        opacity: isLight ? 0.4 : 0.6,
        radius: 10,
        offset: { width: 0, height: 4 },
        elevation: 2,
      }),
    },
    buttonDisabled: {
      opacity: 0.6,
    },
    gameButtonText: {
      color: palette.tint,
      fontWeight: '600',
      fontSize: 13,
    },
    leaveButton: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
      paddingHorizontal: 16,
      paddingVertical: 10,
      borderRadius: 999,
      backgroundColor: leaveBackground,
      ...platformShadow({
        color: surfaceShadow,
        opacity: isLight ? 0.5 : 0.7,
        radius: 12,
        offset: { width: 0, height: 4 },
        elevation: 2,
      }),
    },
    leaveButtonDisabled: {
      backgroundColor: leaveDisabledBackground,
      opacity: 0.7,
    },
    leaveButtonText: {
      color: leaveTint,
      fontWeight: '600',
      fontSize: 13,
    },
    leaveSpinner: {
      color: leaveTint,
    },
    deleteButton: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
      paddingHorizontal: 16,
      paddingVertical: 10,
      borderRadius: 999,
      backgroundColor: deleteBackground,
      ...platformShadow({
        color: surfaceShadow,
        opacity: isLight ? 0.45 : 0.65,
        radius: 12,
        offset: { width: 0, height: 4 },
        elevation: 2,
      }),
    },
    deleteButtonDisabled: {
      backgroundColor: deleteDisabledBackground,
      opacity: 0.7,
    },
    deleteButtonText: {
      color: deleteTint,
      fontWeight: '600',
      fontSize: 13,
    },
    deleteSpinner: {
      color: deleteTint,
    },
    headerCard: {
      padding: 22,
      borderRadius: 28,
      backgroundColor: heroBackground,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor,
      overflow: 'hidden',
      position: 'relative',
      ...platformShadow({
        color: surfaceShadow,
        opacity: isLight ? 0.9 : 0.65,
        radius: 20,
        offset: { width: 0, height: 8 },
        elevation: 4,
      }),
    },
    heroGradientLayer: {
      ...fill,
      opacity: 0.85,
    },
    heroBackdrop: {
      ...fill,
      backgroundColor: heroBackground,
      opacity: isLight ? 0.92 : 0.88,
    },
    heroGlow: {
      position: 'absolute',
      width: 240,
      height: 240,
      borderRadius: 180,
      backgroundColor: `${heroGlowPrimary}33`,
      top: -100,
      right: -80,
    },
    heroGlowSecondary: {
      position: 'absolute',
      width: 230,
      height: 230,
      borderRadius: 150,
      backgroundColor: `${heroGlowSecondary}2b`,
      bottom: -90,
      left: -70,
    },
    heroOrbit: {
      position: 'absolute',
      top: 40,
      right: -30,
      width: 160,
      height: 160,
      borderRadius: 120,
      borderWidth: 1.2,
      borderColor: `${decorCheck}66`,
      opacity: 0.6,
      transform: [{ rotate: '14deg' }],
    },
    heroAccentTop: {
      position: 'absolute',
      top: -36,
      left: -40,
      width: 140,
      height: 140,
      borderRadius: 120,
      backgroundColor: `${decorPlay}24`,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: `${decorPlay}66`,
      transform: [{ rotate: '-18deg' }],
    },
    heroAccentBottom: {
      position: 'absolute',
      bottom: -46,
      right: -20,
      width: 170,
      height: 170,
      borderRadius: 150,
      backgroundColor: `${decorAlert}1a`,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: `${decorAlert}5c`,
      transform: [{ rotate: '12deg' }],
    },
    heroGradientSwatchA: {
      backgroundColor: `${heroGlowSecondary}29`,
    },
    heroGradientSwatchB: {
      backgroundColor: heroBackground,
    },
    heroGradientSwatchC: {
      backgroundColor: `${heroGlowPrimary}2f`,
    },
    headerContent: {
      gap: 18,
    },
    heroHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: 12,
    },
    heroBadge: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
      paddingHorizontal: 14,
      paddingVertical: 8,
      borderRadius: 999,
      backgroundColor: heroBadgeBackground,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: heroBadgeBorder,
    },
    heroBadgeIcon: {
      color: heroBadgeIconColor,
    },
    heroBadgeText: {
      color: heroBadgeTextColor,
      fontWeight: '700',
      fontSize: 13,
    },
    heroTitleStack: {
      gap: 12,
    },
    heroTagline: {
      color: decorCheck,
      textTransform: 'uppercase',
      fontSize: 12,
      letterSpacing: 1.6,
      fontWeight: '700',
    },
    heroTitleFrame: {
      position: 'relative',
      paddingHorizontal: 20,
      paddingVertical: 12,
      borderRadius: 24,
      backgroundColor: titleBackground,
      borderWidth: 1.2,
      borderColor: titleBorder,
      overflow: 'hidden',
      ...platformShadow({
        color: titleGlow,
        opacity: isLight ? 0.5 : 0.7,
        radius: 20,
        offset: { width: 0, height: 8 },
        elevation: 4,
      }),
    },
    heroTitleGlow: {
      ...fill,
      backgroundColor: `${titleGlow}1f`,
      opacity: isLight ? 0.9 : 0.75,
    },
    roomTitle: {
      color: titleText,
      fontSize: 28,
      fontWeight: '800',
      lineHeight: 32,
    },
    gameLabel: {
      color: heroBadgeTextColor,
      fontSize: 13,
      fontWeight: '600',
    },
    heroDividerRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 10,
    },
    heroDividerLine: {
      flex: 1,
      height: 1,
      backgroundColor: `${heroBadgeBorder}66`,
    },
    heroDividerDot: {
      width: 8,
      height: 8,
      borderRadius: 4,
      backgroundColor: decorPlay,
    },
    heroDividerDotSecondary: {
      width: 6,
      height: 6,
      borderRadius: 3,
      backgroundColor: decorAlert,
    },
    statusPill: {
      paddingHorizontal: 12,
      paddingVertical: 6,
      borderRadius: 999,
      ...platformShadow({
        color: surfaceShadow,
        opacity: isLight ? 0.35 : 0.5,
        radius: 8,
        offset: { width: 0, height: 2 },
        elevation: 1,
      }),
    },
    statusLobby: {
      backgroundColor: statusLobby,
    },
    statusInProgress: {
      backgroundColor: statusInProgress,
    },
    statusCompleted: {
      backgroundColor: statusCompleted,
    },
    statusText: {
      fontSize: 12,
      fontWeight: '600',
      color: palette.text,
    },
    metaGrid: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 12,
    },
    metaItem: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 10,
      minWidth: '45%',
      padding: 12,
      borderRadius: 16,
      backgroundColor: actionBackground,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: actionBorder,
      ...platformShadow({
        color: surfaceShadow,
        opacity: isLight ? 0.3 : 0.5,
        radius: 8,
        offset: { width: 0, height: 3 },
        elevation: 2,
      }),
    },
    metaItemIcon: {
      color: palette.tint,
    },
    metaItemCopy: {
      gap: 2,
    },
    metaItemLabel: {
      color: palette.icon,
      fontSize: 12,
      fontWeight: '600',
    },
    metaItemValue: {
      color: palette.text,
      fontWeight: '600',
    },
    loadingRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
    },
    loadingText: {
      color: palette.icon,
    },
    errorCard: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
      padding: 12,
      borderRadius: 14,
      backgroundColor: errorBackground,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: errorBorder,
    },
    errorText: {
      color: errorText,
      fontWeight: '600',
    },
    bodyCard: {
      padding: 20,
      borderRadius: 22,
      backgroundColor: raisedBackground,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor,
      gap: 14,
      ...platformShadow({
        color: surfaceShadow,
        radius: 12,
        opacity: isLight ? 1 : 0.6,
        offset: { width: 0, height: 4 },
        elevation: 2,
      }),
    },
    bodyHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 10,
    },
    bodyHeaderAccent: {
      width: 6,
      height: 28,
      borderRadius: 999,
      backgroundColor: decorCheck,
    },
    bodyHeaderText: {
      color: palette.text,
      fontWeight: '600',
    },
    bodyCopy: {
      color: palette.icon,
      lineHeight: 20,
    },
    footerCard: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 16,
      padding: 20,
      borderRadius: 22,
      backgroundColor: raisedBackground,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor,
      ...platformShadow({
        color: surfaceShadow,
        opacity: isLight ? 0.35 : 0.55,
        radius: 12,
        offset: { width: 0, height: 4 },
        elevation: 2,
      }),
    },
    footerAccent: {
      width: 8,
      height: 32,
      borderRadius: 999,
      backgroundColor: decorAlert,
    },
    footerIcon: {
      color: palette.tint,
    },
    footerCopy: {
      flex: 1,
      gap: 4,
    },
    footerTitle: {
      color: palette.text,
    },
    footerText: {
      color: palette.icon,
      lineHeight: 19,
    },
    tableOnlyCloseButton: {
      position: 'absolute',
      left: 24,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
      paddingHorizontal: 14,
      paddingVertical: 10,
      borderRadius: 999,
      backgroundColor: palette.background,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor,
      ...platformShadow({
        color: surfaceShadow,
        opacity: isLight ? 0.85 : 0.75,
        radius: 12,
        offset: { width: 0, height: 6 },
        elevation: 3,
      }),
    },
    tableOnlyCloseIcon: {
      color: palette.text,
    },
    tableOnlyCloseText: {
      color: palette.text,
      fontWeight: '600',
      fontSize: 13,
    },
  });
}

export type ExplodingCatsRoomStyles = ReturnType<typeof createStyles>;
