/**
 * Central registry of UI sound effects. Assets live in `public/sounds` and are
 * generated by `apps/web/scripts/generate-sound-assets.mjs` (simple synthesized
 * tones — replace with designed audio later without touching call sites).
 */
export const SOUNDS = {
  /** Game won — celebratory ascending arpeggio. */
  win: '/sounds/win.wav',
  /** Game lost / draw — soft descending tone. */
  lose: '/sounds/lose.wav',
  /** Primary CTA press — short blip. */
  click: '/sounds/click.wav',
  /** Currency / reward gained — two-tone chime. */
  coin: '/sounds/coin.wav',
} as const;

export type SoundId = keyof typeof SOUNDS;
