/**
 * Central registry of UI sound effects. Assets live in `public/sounds` and are
 * generated by `apps/web/scripts/generate-sound-assets.mjs` (simple synthesized
 * tones — replace with designed audio later without touching call sites).
 *
 * When NEXT_PUBLIC_CDN_URL is set, paths resolve to the CDN instead of the
 * Next.js public directory — reducing deployment size and improving TTFB.
 */

const CDN = (process.env.NEXT_PUBLIC_CDN_URL || '').replace(/\/+$/, '');
const BASE = CDN ? `${CDN}/sounds` : '/sounds';

export const SOUNDS = {
  /** Game won — celebratory ascending arpeggio. */
  win: `${BASE}/win.wav`,
  /** Game lost / draw — soft descending tone. */
  lose: `${BASE}/lose.wav`,
  /** Primary CTA press — short blip. */
  click: `${BASE}/click.wav`,
  /** Currency / reward gained — two-tone chime. */
  coin: `${BASE}/coin.wav`,
  /** Audio cue: move made on the board. */
  move: `${BASE}/move.wav`,
  /** Audio cue: it is now your turn. */
  turn: `${BASE}/turn.wav`,
  /** Audio cue: attack hit a target. */
  hit: `${BASE}/hit.wav`,
  /** Audio cue: attack missed. */
  miss: `${BASE}/miss.wav`,
  /** Audio cue: ship sunk. */
  sink: `${BASE}/sink.wav`,
  /** Audio cue: game session started. */
  gameStart: `${BASE}/game-start.wav`,
} as const;

export type SoundId = keyof typeof SOUNDS;
