import { GAME_VARIANT } from './variants';

export const THEMATIC_CARD_NAMES: Record<string, Record<string, string>> = {
  [GAME_VARIANT.ADVENTURE]: {
    card_back: 'Adventure Back',
    critical_event: 'Avalanche',
    neutralizer: 'Campfire',
    strike: 'Sword Swing',
    evade: 'Backflip',
    trade: 'Barter',
    reorder: 'Scout Ahead',
    insight: 'Ancient Map',
    cancel: 'Shield Block',
    collection_alpha: 'Golden Idol',
    collection_beta: 'Jeweled Scarab',
    collection_gamma: 'Silver Chalice',
    collection_delta: 'Diamond Skull',
    collection_epsilon: 'Emerald Tablet',
    targeted_strike: 'Bow Shot',
    private_strike: 'Dagger Poke',
    recursive_strike: 'Dual Wield',
    mega_evade: 'Smoke Bomb',
    invert: 'Compass Spin',
    see_future_5x: 'Crystal Ball',
    alter_future_3x: 'Time Hourglass',
    alter_future_5x: 'Prophecy Scroll',
    reveal_future_3x: 'Torchlight',
    share_future_3x: 'Campfire Story',
    draw_bottom: 'Rope Climb',
    swap_top_bottom: 'Skyhook',
    bury: 'Quicksand',
    wildcard: 'Joker Mask',
    mark: 'Eagle Eye',
    steal_draw: 'Pickpocket',
    stash: 'Hidden Cache',
    omniscience: 'God View',
    miracle: 'Divine Intervention',
    smite: 'Holy Bolt',
    rapture: 'Heavenly Ascent',
    critical_implosion: 'Gravity Well',
    containment_field: 'Energy Barrier',
    fission: 'Atomic Burst',
    tribute: 'Sacrifice',
    blackout: 'Shadow Veil',
    vortex: 'Whirlwind',
    essence: 'Soul Spark',
    zen: 'Inner Peace',
    fury: 'Berserk Rage',
    aegis: 'Legendary Shield',
    blight: 'Corrupted Land',
    bloom: 'Life Pulse',
    pulse: 'Mana Ripple',
    gateway: 'Interdimensional Rift',
  },
  [GAME_VARIANT.CRIME]: {
    card_back: 'Crime Back',
    critical_event: 'Police Raid',
    neutralizer: 'Safe House',
    strike: 'Gunshot',
    evade: 'Escape Car',
    trade: 'Launder',
    reorder: 'Wiretap',
    insight: 'Case File',
    cancel: 'Alibi',
    collection_alpha: 'Diamond Loot',
    collection_beta: 'Cash Briefcase',
    collection_gamma: 'Gold Bars',
    collection_delta: 'Art Masterpiece',
    collection_epsilon: 'Blackmail Tape',
    targeted_strike: 'Sniper Shot',
    private_strike: 'Silencer',
    recursive_strike: 'Drive By',
    mega_evade: 'Inner Circle',
    invert: 'Double Cross',
    see_future_5x: 'Surveillance',
    alter_future_3x: 'Rigged Dice',
    alter_future_5x: 'Inside Info',
    reveal_future_3x: 'Search Warrant',
    share_future_3x: 'Tips',
    draw_bottom: 'Underground Tunnel',
    swap_top_bottom: 'Switcheroo',
    bury: 'Cement Shoes',
    wildcard: 'Master Key',
    mark: 'Hit List',
    steal_draw: 'Heist',
    stash: 'Vault',
    omniscience: 'Eye in the Sky',
    miracle: 'Pardon',
    smite: 'Execution',
    rapture: 'Witness Protection',
    critical_implosion: 'Prison Break',
    containment_field: 'Interrogation Room',
    fission: 'Bomb Threat',
    tribute: 'Shakedown',
    blackout: 'City Blackout',
    vortex: 'Money Sink',
    essence: 'Criminal Intent',
    zen: 'Quiet Night',
    fury: 'Vendetta',
    aegis: 'Bodyguard',
    blight: 'Corruption',
    bloom: 'Booming Market',
    pulse: 'Heartbeat',
    gateway: 'Safe Border',
  },
  [GAME_VARIANT.HORROR]: {
    card_back: 'Horror Back',
    critical_event: 'Blood Moon',
    neutralizer: 'Holy Water',
    strike: 'Claw Slash',
    evade: 'Hide in Closet',
    trade: 'Pact',
    reorder: 'Omen',
    insight: 'Forbidden Book',
    cancel: 'Exorcism',
    collection_alpha: 'Relic Box',
    collection_beta: 'Cursed Amulet',
    collection_gamma: 'Old Mirror',
    collection_delta: 'Bone Totem',
    collection_epsilon: 'Rune Stone',
    targeted_strike: 'Ghostly Bite',
    private_strike: 'Whisper',
    recursive_strike: 'Nightmare Rise',
    mega_evade: 'Mist Form',
    invert: 'Mirror Realm',
    see_future_5x: 'Grim Sight',
    alter_future_3x: 'Voodoo Doll',
    alter_future_5x: 'Dark Fate',
    reveal_future_3x: 'Screams',
    share_future_3x: ' Séance',
    draw_bottom: 'Grave Dig',
    swap_top_bottom: 'Possession',
    bury: 'Entombed',
    wildcard: 'Shadow Entity',
    mark: 'Mark of Cain',
    steal_draw: 'Soul Drain',
    stash: 'Crypt',
    omniscience: 'Ancient One View',
    miracle: 'Resurrection',
    smite: 'Death Touch',
    rapture: 'Transcendence',
    critical_implosion: 'Void Collapse',
    containment_field: 'Pentagram',
    fission: 'Plague Burst',
    tribute: 'Offering',
    blackout: 'The Fog',
    vortex: 'Abyss',
    essence: 'Ectoplasm',
    zen: 'Trance',
    fury: 'Demonic Possession',
    aegis: 'Artifact Shield',
    blight: 'Rot',
    bloom: 'Flesh Bloom',
    pulse: 'Terror Wave',
    gateway: 'Hell Portal',
  },
  [GAME_VARIANT.HIGH_ALTITUDE_HIKE]: {
    card_back: 'Hike Back',
    critical_event: 'Blizzard',
    neutralizer: 'Oxygen Tank',
    strike: 'Ice Pick',
    evade: 'Glissade',
    trade: 'Supplies',
    reorder: 'Trail Mark',
    insight: 'Binoculars',
    cancel: 'Anchor Set',
    collection_alpha: 'Summit Flag',
    collection_beta: 'Crampons',
    collection_gamma: 'Carabiner',
    collection_delta: 'Sleeping Bag',
    collection_epsilon: 'First Aid Kit',
    targeted_strike: 'Flare Gun',
    private_strike: 'Snowball',
    recursive_strike: 'Avalanche Fall',
    mega_evade: 'Tent Shelter',
    invert: 'Wind Shift',
    see_future_5x: 'Weather Forecast',
    alter_future_3x: 'Shortcut',
    alter_future_5x: 'Climb Plan',
    reveal_future_3x: 'Horizon',
    share_future_3x: 'Radio Call',
    draw_bottom: 'Crevasse Rescue',
    swap_top_bottom: 'Rope Swap',
    bury: 'Snow Burial',
    wildcard: 'Swiss Knife',
    mark: 'Summit View',
    steal_draw: 'Rucksack Theft',
    stash: 'Base Camp',
    omniscience: 'Drone View',
    miracle: 'Rescue Chopper',
    smite: 'Lightning Strike',
    rapture: 'Summit Reached',
    critical_implosion: 'Ice Crack',
    containment_field: 'Igloo',
    fission: 'Sun Flare',
    tribute: 'Gear Drop',
    blackout: 'Whiteout',
    vortex: 'Wind Tunnel',
    essence: 'Fresh Air',
    zen: 'Peaceful Peak',
    fury: 'Storm Rage',
    aegis: 'Gore-Tex Shell',
    blight: 'Frostbite',
    bloom: 'Alps Flower',
    pulse: 'Mountain Peak Pulse',
    gateway: 'Mountain Pass',
  },
  [GAME_VARIANT.CYBERPUNK]: {
    card_back: 'Cyberpunk Back',
    critical_event: 'System Crash',
    neutralizer: 'ICE Breaker',
    strike: 'Laser Blast',
    evade: 'Neon Dash',
    trade: 'Data Exchange',
    reorder: 'Network Scan',
    insight: 'Neural Link',
    cancel: 'Firewall',
    collection_alpha: 'Data Core',
    collection_beta: 'Credit Chip',
    collection_gamma: 'Cyber Deck',
    collection_delta: 'Memory Module',
    collection_epsilon: 'Bio-Hardware',
    targeted_strike: 'Smart Bullet',
    private_strike: 'Wrist Blade',
    recursive_strike: 'Bot Swarm',
    mega_evade: 'Stealth Cloak',
    invert: 'Code Flip',
    see_future_5x: 'Data Stream',
    alter_future_3x: 'Hack Log',
    alter_future_5x: 'Admin Access',
    reveal_future_3x: 'Decrypt',
    share_future_3x: 'Upload',
    draw_bottom: 'Deep Web Access',
    swap_top_bottom: 'Router Swap',
    bury: 'Delete History',
    wildcard: 'Master Keycard',
    mark: 'Target Locked',
    steal_draw: 'Wallet Hack',
    stash: 'Cloud Storage',
    omniscience: 'Satellite View',
    miracle: 'Zero Day',
    smite: 'System Purge',
    rapture: 'Digital Ascension',
    critical_implosion: 'Logic Bomb',
    containment_field: 'EMP Shield',
    fission: 'Overload',
    tribute: 'Bit Request',
    blackout: 'Night City',
    vortex: 'Bit Hole',
    essence: 'Code Soul',
    zen: 'Static Noise',
    fury: 'Cyber Rage',
    aegis: 'Chameleon Armor',
    blight: 'Malware',
    bloom: 'Viral Growth',
    pulse: 'Data Pulse',
    gateway: 'Mainframe Portal',
  },
  [GAME_VARIANT.UNDERWATER]: {
    card_back: 'Underwater Back',
    critical_event: 'Maelstrom',
    neutralizer: 'Air Bubble',
    strike: 'Harpoon',
    evade: 'Jet Stream',
    trade: 'Cargo Salvage',
    reorder: 'Sonar Ping',
    insight: 'Submarine View',
    cancel: 'Ink Cloud',
    collection_alpha: 'Black Pearl',
    collection_beta: 'Sunken Chest',
    collection_gamma: 'Trident',
    collection_delta: 'Lost Crown',
    collection_epsilon: 'Golden Anchor',
    targeted_strike: 'Torpedo',
    private_strike: 'Sea Urchin',
    recursive_strike: 'Kraken Tentacles',
    mega_evade: 'Camouflage',
    invert: 'Current Shift',
    see_future_5x: 'Glowing Kelp',
    alter_future_3x: 'Tide Change',
    alter_future_5x: 'Ocean Current',
    reveal_future_3x: 'Bio-luminess',
    share_future_3x: 'Whale Song',
    draw_bottom: 'Mariana Trench',
    swap_top_bottom: 'Buoyancy Swap',
    bury: 'Silt Burial',
    wildcard: 'Siren Call',
    mark: 'Harpoon Target',
    steal_draw: 'Pirate Raid',
    stash: 'Cave Cache',
    omniscience: 'Abyss Insight',
    miracle: 'Neptune Grace',
    smite: 'Tidal Wave',
    rapture: 'Surface Reach',
    critical_implosion: 'Pressure Crush',
    containment_field: 'Diving Bell',
    fission: 'Thermal Vent',
    tribute: 'Fish School',
    blackout: 'Midnight Zone',
    vortex: 'Whirlpool',
    essence: 'Brine',
    zen: 'Clam Peace',
    fury: 'Shark Frenzy',
    aegis: 'Turtle Shell',
    blight: 'Oil Spill',
    bloom: 'Coral Growth',
    pulse: 'Pressure Pulse',
    gateway: 'Abyss Gate',
  },
};
