export const gameButtonVariants: Record<string, string> = {
  cyberpunk: [
    'border',
    'border-[var(--cyberpunkPrimary)]',
    'bg-[var(--cyberpunkBg)]',
    'bg-[linear-gradient(160deg,var(--cyberpunkBg)_0%,var(--cyberpunkBgEnd)_100%)]',
    'text-[var(--cyberpunkAccent)]',
    'shadow-[0_4px_2px_var(--cyberpunkPrimary)]',
    'border-t-[rgba(255,255,255,0.15)]',
    'hover:border-[var(--cyberpunkSecondary)]',
    'hover:shadow-[0_10px_22px_var(--cyberpunkPrimary)]',
    'active:shadow-[0_1px_6px_var(--cyberpunkPrimary)]',
  ].join(' '),
  underwater: [
    'border',
    'border-[var(--underwaterPrimary)]',
    'bg-[var(--underwaterBg)]',
    'bg-[linear-gradient(160deg,var(--underwaterBg)_0%,var(--underwaterBgEnd)_100%)]',
    'text-[var(--underwaterPrimary)]',
    'shadow-[0_4px_2px_var(--underwaterPrimary)]',
    'border-t-[rgba(255,255,255,0.12)]',
    'hover:border-[var(--underwaterAccent)]',
    'hover:shadow-[0_10px_22px_var(--underwaterPrimary)]',
    'active:shadow-[0_1px_6px_var(--underwaterPrimary)]',
  ].join(' '),
  crime: [
    'border',
    'border-[var(--crimePrimary)]',
    'bg-[var(--crimeBg)]',
    'bg-[linear-gradient(160deg,var(--crimeBg)_0%,var(--crimeBgEnd)_100%)]',
    'text-[var(--crimeAccent)]',
    'shadow-[0_4px_2px_var(--crimePrimary)]',
    'border-t-[rgba(255,255,255,0.12)]',
    'hover:border-[var(--crimeSecondary)]',
    'hover:shadow-[0_10px_22px_var(--crimePrimary)]',
    'active:shadow-[0_1px_6px_var(--crimePrimary)]',
  ].join(' '),
  horror: [
    'border',
    'border-[var(--horrorPrimary)]',
    'bg-[var(--horrorBg)]',
    'bg-[linear-gradient(160deg,var(--horrorBg)_0%,var(--horrorBgEnd)_100%)]',
    'text-[var(--horrorAccent)]',
    'shadow-[0_4px_2px_var(--horrorPrimary)]',
    'border-t-[rgba(255,255,255,0.1)]',
    'hover:border-[var(--horrorSecondary)]',
    'hover:shadow-[0_10px_22px_var(--horrorPrimary)]',
    'active:shadow-[0_1px_6px_var(--horrorPrimary)]',
  ].join(' '),
  adventure: [
    'border',
    'border-[var(--adventurePrimary)]',
    'bg-[var(--adventureBg)]',
    'bg-[linear-gradient(160deg,var(--adventureBg)_0%,var(--adventureBgEnd)_100%)]',
    'text-[var(--adventureAccent)]',
    'shadow-[0_4px_2px_var(--adventurePrimary)]',
    'border-t-[rgba(255,255,255,0.14)]',
    'hover:border-[var(--adventureSecondary)]',
    'hover:shadow-[0_10px_22px_var(--adventurePrimary)]',
    'active:shadow-[0_1px_6px_var(--adventurePrimary)]',
  ].join(' '),
  'high-altitude-hike': [
    'border',
    'border-[var(--hikePrimary)]',
    'bg-[var(--hikeBg)]',
    'bg-[linear-gradient(160deg,var(--hikeBg)_0%,var(--hikeBgEnd)_100%)]',
    'text-[var(--hikeSecondary)]',
    'shadow-[0_4px_2px_var(--hikePrimary)]',
    'border-t-[rgba(255,255,255,0.14)]',
    'hover:border-[var(--hikeSecondary)]',
    'hover:shadow-[0_10px_22px_var(--hikePrimary)]',
    'active:shadow-[0_1px_6px_var(--hikePrimary)]',
  ].join(' '),
};
