export const sharedButtonVariants = {
  variant: {
    primary: {
      backgroundColor: '$primary',
      background: 'linear-gradient(160deg, $primaryGradientStart 0%, $primaryGradientEnd 100%)',
      color: '$primaryText',
      fontWeight: '800',
      borderColor: '$glassBorder',
      borderTopColor: 'rgba(255,255,255,0.18)',
      borderWidth: 1,
      shadowColor: '$primary',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.55,
      shadowRadius: 2,
      hoverStyle: {
        y: -5,
        opacity: 1,
        backgroundColor: '$accent',
        background: 'linear-gradient(160deg, $accent 0%, $primaryGradientStart 100%)',
        shadowColor: '$primary',
        shadowOffset: { width: 0, height: 10 },
        shadowOpacity: 0.65,
        shadowRadius: 24,
      },
      pressStyle: {
        y: 3,
        backgroundColor: '$primary',
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.4,
        shadowRadius: 2,
      },
    },
    secondary: {
      backgroundColor: '$secondary',
      background: 'linear-gradient(160deg, $secondaryGradientStart 0%, $secondaryGradientEnd 100%)',
      color: '$secondaryText',
      borderColor: '$glassBorder',
      borderTopColor: 'rgba(255,255,255,0.14)',
      borderWidth: 1,
      shadowColor: '$secondary',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.5,
      shadowRadius: 2,
      hoverStyle: {
        y: -5,
        opacity: 1,
        backgroundColor: '$accent',
        background: 'linear-gradient(160deg, $accent 0%, $secondaryGradientStart 100%)',
        shadowColor: '$secondary',
        shadowOffset: { width: 0, height: 10 },
        shadowOpacity: 0.6,
        shadowRadius: 22,
      },
      pressStyle: {
        y: 3,
        backgroundColor: '$secondary',
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.35,
        shadowRadius: 2,
      },
    },
    danger: {
      backgroundColor: '$danger',
      background: 'linear-gradient(160deg, $dangerGradientStart 0%, $dangerGradientEnd 100%)',
      color: '$dangerText',
      borderColor: '$glassBorder',
      borderTopColor: 'rgba(255,255,255,0.14)',
      borderWidth: 1,
      shadowColor: '$danger',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.55,
      shadowRadius: 2,
      hoverStyle: {
        y: -5,
        opacity: 1,
        shadowColor: '$danger',
        shadowOffset: { width: 0, height: 10 },
        shadowOpacity: 0.65,
        shadowRadius: 24,
      },
      pressStyle: {
        y: 3,
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.4,
        shadowRadius: 2,
      },
    },
    glass: {
      backgroundColor: '$glassBg',
      color: '$color',
      borderColor: '$glassBorder',
      borderTopColor: 'rgba(255,255,255,0.2)',
      borderWidth: 1,
      backdropFilter: 'blur(12px)',
      shadowColor: 'rgba(0,0,0,0.4)',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 1,
      shadowRadius: 2,
      hoverStyle: {
        y: -5,
        opacity: 1,
        backgroundColor: '$glassBgHover',
        borderColor: '$glassBorderHover',
        backdropFilter: 'blur(20px)',
        shadowColor: '$shadowColor',
        shadowOffset: { width: 0, height: 10 },
        shadowOpacity: 0.35,
        shadowRadius: 16,
      },
      pressStyle: {
        y: 3,
        shadowOffset: { width: 0, height: 1 },
        shadowRadius: 2,
        shadowOpacity: 0.6,
      },
    },
    ghost: {
      backgroundColor: 'transparent',
      borderWidth: 0,
      shadowOpacity: 0,
      hoverStyle: {
        y: -3,
        opacity: 1,
        backgroundColor: '$glassBgHover',
        shadowColor: 'rgba(0,0,0,0.2)',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 1,
        shadowRadius: 8,
      },
      pressStyle: {
        y: 2,
        shadowOpacity: 0,
      },
    },
    outline: {
      backgroundColor: 'transparent',
      borderColor: '$borderColor',
      // Without an explicit color the Button's internal Typography (which
      // uses color="inherit") falls back to Tamagui's default dark text —
      // invisible against dark theme. Theme `$color` token resolves on both
      // light and dark.
      color: '$color',
      shadowColor: 'rgba(0,0,0,0.3)',
      shadowOffset: { width: 0, height: 3 },
      shadowOpacity: 1,
      shadowRadius: 1,
      hoverStyle: {
        y: -4,
        opacity: 1,
        backgroundColor: '$glassBgHover',
        borderColor: '$glassBorderHover',
        shadowOffset: { width: 0, height: 8 },
        shadowRadius: 12,
      },
      pressStyle: {
        y: 2,
        shadowOffset: { width: 0, height: 1 },
        shadowRadius: 1,
      },
    },
    icon: {
      padding: 0,
      backgroundColor: 'rgba(255, 255, 255, 0.05)',
      borderColor: 'rgba(255, 255, 255, 0.1)',
      borderWidth: 1,
      borderRadius: 999,
      aspectRatio: 1,
      color: '$color',
      shadowOpacity: 0,
      justifyContent: 'center',
      alignItems: 'center',
      hoverStyle: {
        y: -2,
        opacity: 1,
        transform: 'rotate(180deg) scale(1.1)',
        backgroundColor: 'rgba(255, 255, 255, 0.15)',
        borderColor: 'rgba(255, 255, 255, 0.25)',
        shadowColor: 'rgba(0,0,0,0.3)',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 1,
        shadowRadius: 10,
      },
      pressStyle: {
        y: 1,
        scale: 0.95,
        backgroundColor: 'rgba(255, 255, 255, 0.1)',
        shadowOpacity: 0,
      },
    },
    link: {
      backgroundColor: 'transparent',
      padding: 0,
      height: 'auto',
      shadowOpacity: 0,
      hoverStyle: {
        y: 0,
        opacity: 0.7,
        shadowOpacity: 0,
      },
    },
    chip: {
      backgroundColor: 'rgba(255, 255, 255, 0.05)',
      color: '$color',
      borderColor: 'rgba(255, 255, 255, 0.1)',
      borderWidth: 1,
      borderRadius: '$4',
      height: 28,
      px: '$3',
      shadowColor: 'rgba(0,0,0,0.3)',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 1,
      shadowRadius: 1,
      hoverStyle: {
        y: -3,
        opacity: 1,
        backgroundColor: '$glassBgHover',
        borderColor: '$glassBorderHover',
        shadowOffset: { width: 0, height: 5 },
        shadowRadius: 8,
      },
      pressStyle: {
        y: 2,
        shadowOffset: { width: 0, height: 0 },
        shadowRadius: 1,
      },
    },
    listItem: {
      backgroundColor: 'transparent',
      justifyContent: 'flex-start',
      width: '100%',
      shadowOpacity: 0,
      height: 44,
      px: '$4',
      color: '$color',
      hoverStyle: {
        y: 0,
        opacity: 1,
        backgroundColor: '$glassBgHover',
        shadowOpacity: 0,
      },
    },
    neutral: {
      backgroundColor: '$background',
      borderColor: '$borderColor',
      shadowColor: 'rgba(0,0,0,0.35)',
      shadowOffset: { width: 0, height: 3 },
      shadowOpacity: 1,
      shadowRadius: 1,
      hoverStyle: {
        y: -4,
        opacity: 1,
        backgroundColor: '$glassBg',
        borderColor: '$glassBorderHover',
        shadowOffset: { width: 0, height: 8 },
        shadowRadius: 10,
      },
      pressStyle: {
        y: 2,
        shadowOffset: { width: 0, height: 1 },
        shadowRadius: 1,
      },
    },
    success: {
      backgroundColor: '$success',
      color: '$successText',
      shadowColor: '$success',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.5,
      shadowRadius: 2,
      hoverStyle: {
        y: -5,
        opacity: 1,
        backgroundColor: '$success',
        shadowColor: '$success',
        shadowOffset: { width: 0, height: 10 },
        shadowOpacity: 0.6,
        shadowRadius: 18,
      },
      pressStyle: {
        y: 3,
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.35,
        shadowRadius: 2,
      },
    },
    warning: {
      backgroundColor: '$warning',
      color: '$warningText',
      shadowColor: '$warning',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.5,
      shadowRadius: 2,
      hoverStyle: {
        y: -5,
        opacity: 1,
        backgroundColor: '$warning',
        shadowColor: '$warning',
        shadowOffset: { width: 0, height: 10 },
        shadowOpacity: 0.6,
        shadowRadius: 18,
      },
      pressStyle: {
        y: 3,
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.35,
        shadowRadius: 2,
      },
    },
    info: {
      backgroundColor: '$info',
      color: '$infoText',
      shadowColor: '$info',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.5,
      shadowRadius: 2,
      hoverStyle: {
        y: -5,
        opacity: 1,
        backgroundColor: '$info',
        shadowColor: '$info',
        shadowOffset: { width: 0, height: 10 },
        shadowOpacity: 0.6,
        shadowRadius: 18,
      },
      pressStyle: {
        y: 3,
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.35,
        shadowRadius: 2,
      },
    },
    victory: {
      backgroundColor: '#FFD700',
      background: 'linear-gradient(160deg, #ffe866 0%, #ff9500 100%)',
      borderWidth: 0,
      borderTopColor: 'rgba(255,255,255,0.35)',
      color: '#1a1a1a',
      shadowColor: 'rgba(255, 165, 0, 0.7)',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 1,
      shadowRadius: 2,
      hoverStyle: {
        y: -6,
        scale: 1.04,
        background: 'linear-gradient(160deg, #fff07a 0%, #ffb500 100%)',
        shadowColor: 'rgba(255, 215, 0, 0.8)',
        shadowOffset: { width: 0, height: 12 },
        shadowOpacity: 1,
        shadowRadius: 28,
      },
      pressStyle: {
        y: 3,
        scale: 0.98,
        shadowOffset: { width: 0, height: 1 },
        shadowRadius: 4,
        shadowOpacity: 0.8,
      },
    },
  },
  pulse: {
    true: { animation: 'pulse' },
  },
  pill: {
    true: { borderRadius: 999 },
  },
  jump: {
    true: { animation: 'jump' },
  },
} as const;

export const sharedButtonSizes = {
  $uiSize: {
    sm: { height: 36, px: '$4', py: '$2', borderRadius: '$3' },
    md: { height: 48, px: '$6', py: '$3', borderRadius: '$4' },
    lg: { height: 60, px: '$8', py: '$4', borderRadius: '$5' },
  },
} as const;
