export const sharedButtonVariants = {
  variant: {
    primary: {
      backgroundColor: '$primary',
      background: 'linear-gradient(135deg, $primaryGradientStart 0%, $primaryGradientEnd 100%)',
      borderColor: '$glassBorder',
      borderWidth: 1,
      hoverStyle: {
        y: -3,
        opacity: 1,
        backgroundColor: '$primaryGradientStart',
        background: 'linear-gradient(135deg, $accent 0%, $primaryGradientStart 100%)',
        shadowColor: '$primary',
        shadowOffset: { width: 0, height: 8 },
        shadowOpacity: 0.5,
        shadowRadius: 20,
      },
    },
    secondary: {
      backgroundColor: '$secondary',
      background: 'linear-gradient(135deg, $secondaryGradientStart 0%, $secondaryGradientEnd 100%)',
      borderColor: '$glassBorder',
      borderWidth: 1,
      hoverStyle: {
        y: -3,
        opacity: 1,
        backgroundColor: '$secondaryGradientStart',
        background: 'linear-gradient(135deg, $accent 0%, $secondaryGradientStart 100%)',
        shadowColor: '$secondary',
        shadowOffset: { width: 0, height: 8 },
        shadowOpacity: 0.45,
        shadowRadius: 18,
      },
    },
    danger: {
      backgroundColor: '$danger',
      background: 'linear-gradient(135deg, $dangerGradientStart 0%, $dangerGradientEnd 100%)',
      borderColor: '$glassBorder',
      borderWidth: 1,
      hoverStyle: {
        y: -3,
        opacity: 1,
        backgroundColor: '$dangerGradientStart',
        background: 'linear-gradient(135deg, $dangerGradientStart 0%, $dangerGradientEnd 100%)',
        shadowColor: '$danger',
        shadowOffset: { width: 0, height: 8 },
        shadowOpacity: 0.5,
        shadowRadius: 20,
      },
    },
    glass: {
      backgroundColor: '$glassBg',
      borderColor: '$glassBorder',
      borderWidth: 1,
      backdropFilter: 'blur(12px)',
      hoverStyle: {
        y: -3,
        opacity: 1,
        backgroundColor: '$glassBgHover',
        borderColor: '$glassBorderHover',
        backdropFilter: 'blur(20px)',
        shadowColor: '$shadowColor',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.2,
        shadowRadius: 10,
      },
    },
    ghost: {
      backgroundColor: 'transparent',
      borderWidth: 0,
      hoverStyle: {
        y: -2,
        opacity: 1,
        backgroundColor: '$glassBgHover',
      },
    },
    outline: {
      backgroundColor: 'transparent',
      borderColor: '$borderColor',
      hoverStyle: {
        y: -2,
        opacity: 1,
        backgroundColor: '$glassBgHover',
        borderColor: '$glassBorderHover',
      },
    },
    icon: {
      padding: 0,
      backgroundColor: 'transparent',
      hoverStyle: {
        y: -1,
        opacity: 1,
        scale: 1.12,
        backgroundColor: '$glassBgHover',
      },
    },
    link: {
      backgroundColor: 'transparent',
      padding: 0,
      height: 'auto',
      hoverStyle: {
        y: 0,
        opacity: 0.7,
      },
    },
    chip: {
      borderRadius: '$4',
      height: 28,
      px: '$3',
      hoverStyle: {
        y: -1,
        opacity: 1,
        backgroundColor: '$glassBgHover',
        borderColor: '$glassBorderHover',
      },
    },
    listItem: {
      backgroundColor: 'transparent',
      justifyContent: 'flex-start',
      width: '100%',
      hoverStyle: {
        y: 0,
        opacity: 1,
        backgroundColor: '$glassBg',
      },
    },
    neutral: {
      backgroundColor: '$background',
      borderColor: '$borderColor',
      hoverStyle: {
        y: -2,
        opacity: 1,
        backgroundColor: '$glassBg',
        borderColor: '$glassBorderHover',
      },
    },
    success: {
      backgroundColor: '$success',
      hoverStyle: {
        y: -2,
        opacity: 1,
        backgroundColor: '$success',
        shadowColor: '$success',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.45,
        shadowRadius: 14,
      },
    },
    warning: {
      backgroundColor: '$warning',
      hoverStyle: {
        y: -2,
        opacity: 1,
        backgroundColor: '$warning',
        shadowColor: '$warning',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.45,
        shadowRadius: 14,
      },
    },
    info: {
      backgroundColor: '$info',
      hoverStyle: {
        y: -2,
        opacity: 1,
        backgroundColor: '$info',
        shadowColor: '$info',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.45,
        shadowRadius: 14,
      },
    },
    victory: {
      backgroundColor: '#FFD700',
      background: 'linear-gradient(45deg, #ffd700, #ffa500)',
      borderWidth: 0,
      color: '#1a1a1a',
      hoverStyle: {
        y: -3,
        scale: 1.05,
        backgroundColor: '#ffa500',
        shadowColor: 'rgba(255, 215, 0, 0.4)',
        shadowOffset: { width: 0, height: 8 },
        shadowOpacity: 0.5,
        shadowRadius: 20,
      },
    },
  },
} as const;

export const sharedButtonSizes = {
  buttonSize: {
    sm: { height: 36, px: '$4', py: '$2', borderRadius: '$3' },
    md: { height: 48, px: '$6', py: '$3', borderRadius: '$4' },
    lg: { height: 60, px: '$8', py: '$4', borderRadius: '$5' },
  },
} as const;
