import { Button as TButton, styled, YStack, TamaguiComponent } from 'tamagui';
import { sharedButtonVariants, sharedButtonSizes } from './SharedButtonStyles';

export const Shimmer: TamaguiComponent = styled(YStack, {
  position: 'absolute',
  inset: 0,
  pointerEvents: 'none',
  background: 'linear-gradient(90deg, transparent, $glassBorder, transparent)',
  x: '-100%',
});

export const StyledButton: TamaguiComponent = styled(TButton, {
  name: 'AppButton',
  borderRadius: '$4',
  borderWidth: 1,
  borderColor: 'transparent',
  position: 'relative',
  overflow: 'hidden',
  shadowColor: 'rgba(0,0,0,0.5)',
  shadowOffset: { width: 0, height: 4 },
  shadowOpacity: 1,
  shadowRadius: 2,

  hoverStyle: {
    y: -5,
    scale: 1.02,
    borderColor: '$borderColorHover',
    opacity: 1,
    shadowOffset: { width: 0, height: 10 },
    shadowRadius: 6,
    shadowOpacity: 1,
  },
  focusStyle: {
    borderColor: '$primary',
    borderWidth: 2,
    outlineColor: 'transparent',
  },
  pressStyle: process.env.NEXT_PUBLIC_E2E === 'true' ? undefined : {
    scale: 0.98,
    y: 3,
    opacity: 0.95,
    shadowOffset: { width: 0, height: 1 },
    shadowRadius: 1,
    shadowOpacity: 0.8,
  },

  variants: {
    ...sharedButtonSizes,
    ...sharedButtonVariants,

    fullWidth: {
      true: { width: '100%' },
    },

    isActive: {
      true: {
        y: -3,
        shadowOffset: { width: 0, height: 6 },
        shadowRadius: 3,
        shadowOpacity: 1,
      },
      false: {},
    },

    disabled: {
      true: {
        opacity: 0.4,
        cursor: 'not-allowed',
        pointerEvents: 'none',
      },
      false: {
        pointerEvents: 'auto',
      },
    },

    gameVariant: {
      cyberpunk: {
        background: 'linear-gradient(160deg, $cyberpunkBg 0%, $cyberpunkBgEnd 100%)',
        borderColor: '$cyberpunkPrimary',
        borderTopColor: 'rgba(255,255,255,0.15)',
        borderWidth: 1,
        color: '$cyberpunkAccent',
        shadowColor: '$cyberpunkSecondary',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.7,
        shadowRadius: 2,
        hoverStyle: {
          y: -5,
          opacity: 1,
          borderColor: '$cyberpunkSecondary',
          shadowColor: '$cyberpunkSecondary',
          shadowOffset: { width: 0, height: 10 },
          shadowOpacity: 1,
          shadowRadius: 24,
        },
        pressStyle: {
          y: 3,
          shadowOffset: { width: 0, height: 1 },
          shadowOpacity: 0.5,
          shadowRadius: 6,
        },
      },
      underwater: {
        background: 'linear-gradient(160deg, $underwaterBg 0%, $underwaterBgEnd 100%)',
        borderColor: '$underwaterPrimary',
        borderTopColor: 'rgba(255,255,255,0.12)',
        borderWidth: 1,
        color: '$underwaterPrimary',
        shadowColor: '$underwaterPrimary',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.5,
        shadowRadius: 2,
        hoverStyle: {
          y: -5,
          opacity: 1,
          borderColor: '$underwaterAccent',
          shadowColor: '$underwaterPrimary',
          shadowOffset: { width: 0, height: 10 },
          shadowOpacity: 0.8,
          shadowRadius: 22,
        },
        pressStyle: {
          y: 3,
          shadowOffset: { width: 0, height: 1 },
          shadowOpacity: 0.4,
          shadowRadius: 4,
        },
      },
      crime: {
        background: 'linear-gradient(160deg, $crimeBg 0%, $crimeBgEnd 100%)',
        borderColor: '$crimePrimary',
        borderTopColor: 'rgba(255,255,255,0.12)',
        borderWidth: 1,
        color: '$crimeAccent',
        shadowColor: '$crimePrimary',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.6,
        shadowRadius: 2,
        hoverStyle: {
          y: -5,
          opacity: 1,
          borderColor: '$crimeSecondary',
          shadowColor: '$crimePrimary',
          shadowOffset: { width: 0, height: 10 },
          shadowOpacity: 0.9,
          shadowRadius: 22,
        },
        pressStyle: {
          y: 3,
          shadowOffset: { width: 0, height: 1 },
          shadowOpacity: 0.45,
          shadowRadius: 4,
        },
      },
      horror: {
        background: 'linear-gradient(160deg, $horrorBg 0%, $horrorBgEnd 100%)',
        borderColor: '$horrorPrimary',
        borderTopColor: 'rgba(255,255,255,0.1)',
        borderWidth: 1,
        color: '$horrorAccent',
        shadowColor: '$horrorPrimary',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.5,
        shadowRadius: 2,
        hoverStyle: {
          y: -5,
          opacity: 1,
          borderColor: '$horrorSecondary',
          shadowColor: '$horrorPrimary',
          shadowOffset: { width: 0, height: 10 },
          shadowOpacity: 0.8,
          shadowRadius: 22,
        },
        pressStyle: {
          y: 3,
          shadowOffset: { width: 0, height: 1 },
          shadowOpacity: 0.4,
          shadowRadius: 4,
        },
      },
      adventure: {
        background: 'linear-gradient(160deg, $adventureBg 0%, $adventureBgEnd 100%)',
        borderColor: '$adventurePrimary',
        borderTopColor: 'rgba(255,255,255,0.14)',
        borderWidth: 1,
        color: '$adventureAccent',
        shadowColor: '$adventurePrimary',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.6,
        shadowRadius: 2,
        hoverStyle: {
          y: -5,
          opacity: 1,
          borderColor: '$adventureSecondary',
          shadowColor: '$adventurePrimary',
          shadowOffset: { width: 0, height: 10 },
          shadowOpacity: 0.9,
          shadowRadius: 22,
        },
        pressStyle: {
          y: 3,
          shadowOffset: { width: 0, height: 1 },
          shadowOpacity: 0.45,
          shadowRadius: 4,
        },
      },
      'high-altitude-hike': {
        background: 'linear-gradient(160deg, $hikeBg 0%, $hikeBgEnd 100%)',
        borderColor: '$hikePrimary',
        borderTopColor: 'rgba(255,255,255,0.14)',
        borderWidth: 1,
        color: '$hikeSecondary',
        shadowColor: '$hikePrimary',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.5,
        shadowRadius: 2,
        hoverStyle: {
          y: -5,
          opacity: 1,
          borderColor: '$hikeSecondary',
          shadowColor: '$hikePrimary',
          shadowOffset: { width: 0, height: 10 },
          shadowOpacity: 0.8,
          shadowRadius: 22,
        },
        pressStyle: {
          y: 3,
          shadowOffset: { width: 0, height: 1 },
          shadowOpacity: 0.4,
          shadowRadius: 4,
        },
      },
    },

  } as const,

  defaultVariants: {
    buttonSize: 'md',
    variant: 'secondary',
  },
});
