/**
 * Below are the colors that are used in the app. The colors are defined in the light and dark mode.
 * There are many other ways to style your app. For example, [Nativewind](https://www.nativewind.dev/), [Tamagui](https://tamagui.dev/), [unistyles](https://reactnativeunistyles.vercel.app), etc.
 */

const tintColorLight = '#0a7ea4';
const tintColorDark = '#fff';

export const Colors = {
  light: {
    text: '#11181C',
    background: '#fff',
    tint: tintColorLight,
    icon: '#687076',
    cardBackground: '#F6F8FC',
    cardBorder: '#D8DFEA',
    tabIconDefault: '#687076',
    tabIconSelected: tintColorLight,
    statusConnected: '#2ecc40',
    statusDisconnected: '#ff4136',
    error: '#ff4136',
    destructive: '#ff4136',
    warning: '#f59e0b',
    gameTable: {
      surface: '#F6F8FC',
      raised: '#E7EDF7',
      border: '#D8DFEA',
      shadow: 'rgba(15, 23, 42, 0.08)',
      playerSelf: '#ECFEFF',
      playerCurrent: '#FEF3C7',
      destructiveBg: '#FEE2E2',
      destructiveText: '#991B1B',
      playerIcon: '#0F172A',
    },
    gameRoom: {
      raisedBackground: '#E9EEF6',
      border: '#D8DFEA',
      surfaceShadow: 'rgba(15, 23, 42, 0.08)',
      heroBackground: '#E0F2FE',
      heroGlowPrimary: '#C4B5FD',
      heroGlowSecondary: '#FCD34D',
      topBarSurface: '#EDF2FF',
      topBarBorder: '#C8D5F4',
      heroBadgeBackground: '#EEF2FF',
      heroBadgeBorder: '#C7D2FE',
      heroBadgeIcon: '#4338CA',
      heroBadgeText: '#1E3A8A',
      actionBackground: '#FFFFFF',
      actionBorder: '#DAE4F7',
      statusLobby: '#DCFCE7',
      statusInProgress: '#FDE68A',
      statusCompleted: '#E2E8F0',
      leaveBackground: '#FEE2E2',
      leaveDisabledBackground: '#E2E8F0',
      leaveTint: '#B91C1C',
      deleteBackground: '#F97316',
      deleteDisabledBackground: '#E2E8F0',
      deleteTint: '#7C2D12',
      errorBackground: '#F9731620',
      errorBorder: '#F9731655',
      errorText: '#F97316',
    },
  },
  dark: {
    text: '#ECEDEE',
    background: '#151718',
    tint: tintColorDark,
    icon: '#9BA1A6',
    cardBackground: '#1F2228',
    cardBorder: '#32353D',
    tabIconDefault: '#9BA1A6',
    tabIconSelected: tintColorDark,
    statusConnected: '#2ecc40',
    statusDisconnected: '#ff4136',
    error: '#ff4136',
    destructive: '#ff6b6b',
    warning: '#fbbf24',
    gameTable: {
      surface: '#1E2229',
      raised: '#262A32',
      border: '#33373E',
      shadow: 'rgba(0, 0, 0, 0.45)',
      playerSelf: '#11252A',
      playerCurrent: '#3B2E11',
      destructiveBg: '#3A2020',
      destructiveText: '#FECACA',
      playerIcon: '#F1F5F9',
    },
    gameRoom: {
      raisedBackground: '#262A31',
      border: '#33373D',
      surfaceShadow: 'rgba(8, 10, 15, 0.45)',
      heroBackground: '#1E2A3A',
      heroGlowPrimary: '#2F2A5A',
      heroGlowSecondary: '#3C2F1A',
      topBarSurface: '#1F2736',
      topBarBorder: '#2E3A4F',
      heroBadgeBackground: '#2E3352',
      heroBadgeBorder: '#3F4468',
      heroBadgeIcon: '#C4B5FD',
      heroBadgeText: '#E0E7FF',
      actionBackground: '#282F3D',
      actionBorder: '#3B455A',
      statusLobby: '#1D3A28',
      statusInProgress: '#42381F',
      statusCompleted: '#2B3038',
      leaveBackground: '#3A2020',
      leaveDisabledBackground: '#31353C',
      leaveTint: '#FCA5A5',
      deleteBackground: '#4A1D0D',
      deleteDisabledBackground: '#31353C',
      deleteTint: '#FCD7BE',
      errorBackground: '#F9731626',
      errorBorder: '#F9731655',
      errorText: '#FBD38D',
    },
  },
};
