// Automatically generated by scripts/spritesheet/generate_shop_spritesheets.js
// Do not edit directly.

import { resolveAssetUrl } from '../../utils/resolveAssetUrl';

export interface SpriteInfo {
  index: number;
  spritesheet: string;
  cols: number;
  size: number;
}

const _AVATAR_SPRITE_MAP: Record<string, Omit<SpriteInfo, 'spritesheet'>> = {
  '/shop/avatars/bear-cyber.png': { index: 0, cols: 6, size: 128 },
  '/shop/avatars/cat-01.png': { index: 1, cols: 6, size: 128 },
  '/shop/avatars/cat-bengal.png': { index: 2, cols: 6, size: 128 },
  '/shop/avatars/cat-persian.png': { index: 3, cols: 6, size: 128 },
  '/shop/avatars/cat-siam.png': { index: 4, cols: 6, size: 128 },
  '/shop/avatars/cheetah-cyber.png': { index: 5, cols: 6, size: 128 },
  '/shop/avatars/cosmic-01.png': { index: 6, cols: 6, size: 128 },
  '/shop/avatars/default-01.png': { index: 7, cols: 6, size: 128 },
  '/shop/avatars/dragon-01.png': { index: 8, cols: 6, size: 128 },
  '/shop/avatars/dragon-cyber.png': { index: 9, cols: 6, size: 128 },
  '/shop/avatars/eagle-01.png': { index: 10, cols: 6, size: 128 },
  '/shop/avatars/eagle-cyber.png': { index: 11, cols: 6, size: 128 },
  '/shop/avatars/falcon-cyber.png': { index: 12, cols: 6, size: 128 },
  '/shop/avatars/fox-01.png': { index: 13, cols: 6, size: 128 },
  '/shop/avatars/gorilla-cyber.png': { index: 14, cols: 6, size: 128 },
  '/shop/avatars/leopard-cyber.png': { index: 15, cols: 6, size: 128 },
  '/shop/avatars/lion-01.png': { index: 16, cols: 6, size: 128 },
  '/shop/avatars/lion-cyber.png': { index: 17, cols: 6, size: 128 },
  '/shop/avatars/panda-cyber.png': { index: 18, cols: 6, size: 128 },
  '/shop/avatars/panther-01.png': { index: 19, cols: 6, size: 128 },
  '/shop/avatars/phoenix-01.png': { index: 20, cols: 6, size: 128 },
  '/shop/avatars/phoenix-cyber.png': { index: 21, cols: 6, size: 128 },
  '/shop/avatars/shark-01.png': { index: 22, cols: 6, size: 128 },
  '/shop/avatars/shark-cyber.png': { index: 23, cols: 6, size: 128 },
  '/shop/avatars/tiger-01.png': { index: 24, cols: 6, size: 128 },
  '/shop/avatars/tiger-cyber.png': { index: 25, cols: 6, size: 128 },
  '/shop/avatars/wolf-01.png': { index: 26, cols: 6, size: 128 },
  '/shop/avatars/wolf-cyber.png': { index: 27, cols: 6, size: 128 },
};

const AVATAR_SPRITESHEET = resolveAssetUrl('/shop/avatars_spritesheet.webp');

export const AVATAR_SPRITE_MAP: Record<string, SpriteInfo> = Object.fromEntries(
  Object.entries(_AVATAR_SPRITE_MAP).map(([key, val]) => [
    key,
    { ...val, spritesheet: AVATAR_SPRITESHEET },
  ]),
);

const _BADGE_SPRITE_MAP: Record<string, Omit<SpriteInfo, 'spritesheet'>> = {
  '/shop/badges/archon.png': { index: 0, cols: 4, size: 96 },
  '/shop/badges/ascendant.png': { index: 1, cols: 4, size: 96 },
  '/shop/badges/champion.png': { index: 2, cols: 4, size: 96 },
  '/shop/badges/conqueror.png': { index: 3, cols: 4, size: 96 },
  '/shop/badges/elite.png': { index: 4, cols: 4, size: 96 },
  '/shop/badges/gladiator.png': { index: 5, cols: 4, size: 96 },
  '/shop/badges/grandmaster.png': { index: 6, cols: 4, size: 96 },
  '/shop/badges/guardian.png': { index: 7, cols: 4, size: 96 },
  '/shop/badges/juggernaut.png': { index: 8, cols: 4, size: 96 },
  '/shop/badges/legend.png': { index: 9, cols: 4, size: 96 },
  '/shop/badges/mythic.png': { index: 10, cols: 4, size: 96 },
  '/shop/badges/newcomer.png': { index: 11, cols: 4, size: 96 },
  '/shop/badges/nexus.png': { index: 12, cols: 4, size: 96 },
  '/shop/badges/paladin.png': { index: 13, cols: 4, size: 96 },
  '/shop/badges/paragon.png': { index: 14, cols: 4, size: 96 },
  '/shop/badges/scout.png': { index: 15, cols: 4, size: 96 },
  '/shop/badges/sovereign.png': { index: 16, cols: 4, size: 96 },
  '/shop/badges/titan.png': { index: 17, cols: 4, size: 96 },
  '/shop/badges/vanguard.png': { index: 18, cols: 4, size: 96 },
  '/shop/badges/veteran.png': { index: 19, cols: 4, size: 96 },
  '/shop/badges/warlord.png': { index: 20, cols: 4, size: 96 },
};

const BADGE_SPRITESHEET = resolveAssetUrl('/shop/badges_spritesheet.webp');

export const BADGE_SPRITE_MAP: Record<string, SpriteInfo> = Object.fromEntries(
  Object.entries(_BADGE_SPRITE_MAP).map(([key, val]) => [
    key,
    { ...val, spritesheet: BADGE_SPRITESHEET },
  ]),
);
