// Automatically generated by scripts/spritesheet/generate_shop_spritesheets.js
// Do not edit directly.

export interface SpriteInfo {
  index: number;
  spritesheet: string;
  cols: number;
  size: number;
}

export const AVATAR_SPRITE_MAP: Record<string, SpriteInfo> = {
  '/shop/avatars/bear-cyber.png': { index: 0, spritesheet: '/shop/avatars_spritesheet.png', cols: 6, size: 512 },
  '/shop/avatars/cat-01.png': { index: 1, spritesheet: '/shop/avatars_spritesheet.png', cols: 6, size: 512 },
  '/shop/avatars/cat-bengal.png': { index: 2, spritesheet: '/shop/avatars_spritesheet.png', cols: 6, size: 512 },
  '/shop/avatars/cat-persian.png': { index: 3, spritesheet: '/shop/avatars_spritesheet.png', cols: 6, size: 512 },
  '/shop/avatars/cat-siam.png': { index: 4, spritesheet: '/shop/avatars_spritesheet.png', cols: 6, size: 512 },
  '/shop/avatars/cheetah-cyber.png': { index: 5, spritesheet: '/shop/avatars_spritesheet.png', cols: 6, size: 512 },
  '/shop/avatars/cosmic-01.png': { index: 6, spritesheet: '/shop/avatars_spritesheet.png', cols: 6, size: 512 },
  '/shop/avatars/default-01.png': { index: 7, spritesheet: '/shop/avatars_spritesheet.png', cols: 6, size: 512 },
  '/shop/avatars/dragon-01.png': { index: 8, spritesheet: '/shop/avatars_spritesheet.png', cols: 6, size: 512 },
  '/shop/avatars/dragon-cyber.png': { index: 9, spritesheet: '/shop/avatars_spritesheet.png', cols: 6, size: 512 },
  '/shop/avatars/eagle-01.png': { index: 10, spritesheet: '/shop/avatars_spritesheet.png', cols: 6, size: 512 },
  '/shop/avatars/eagle-cyber.png': { index: 11, spritesheet: '/shop/avatars_spritesheet.png', cols: 6, size: 512 },
  '/shop/avatars/falcon-cyber.png': { index: 12, spritesheet: '/shop/avatars_spritesheet.png', cols: 6, size: 512 },
  '/shop/avatars/fox-01.png': { index: 13, spritesheet: '/shop/avatars_spritesheet.png', cols: 6, size: 512 },
  '/shop/avatars/gorilla-cyber.png': { index: 14, spritesheet: '/shop/avatars_spritesheet.png', cols: 6, size: 512 },
  '/shop/avatars/leopard-cyber.png': { index: 15, spritesheet: '/shop/avatars_spritesheet.png', cols: 6, size: 512 },
  '/shop/avatars/lion-01.png': { index: 16, spritesheet: '/shop/avatars_spritesheet.png', cols: 6, size: 512 },
  '/shop/avatars/lion-cyber.png': { index: 17, spritesheet: '/shop/avatars_spritesheet.png', cols: 6, size: 512 },
  '/shop/avatars/panda-cyber.png': { index: 18, spritesheet: '/shop/avatars_spritesheet.png', cols: 6, size: 512 },
  '/shop/avatars/panther-01.png': { index: 19, spritesheet: '/shop/avatars_spritesheet.png', cols: 6, size: 512 },
  '/shop/avatars/phoenix-01.png': { index: 20, spritesheet: '/shop/avatars_spritesheet.png', cols: 6, size: 512 },
  '/shop/avatars/phoenix-cyber.png': { index: 21, spritesheet: '/shop/avatars_spritesheet.png', cols: 6, size: 512 },
  '/shop/avatars/shark-01.png': { index: 22, spritesheet: '/shop/avatars_spritesheet.png', cols: 6, size: 512 },
  '/shop/avatars/shark-cyber.png': { index: 23, spritesheet: '/shop/avatars_spritesheet.png', cols: 6, size: 512 },
  '/shop/avatars/tiger-01.png': { index: 24, spritesheet: '/shop/avatars_spritesheet.png', cols: 6, size: 512 },
  '/shop/avatars/tiger-cyber.png': { index: 25, spritesheet: '/shop/avatars_spritesheet.png', cols: 6, size: 512 },
  '/shop/avatars/wolf-01.png': { index: 26, spritesheet: '/shop/avatars_spritesheet.png', cols: 6, size: 512 },
  '/shop/avatars/wolf-cyber.png': { index: 27, spritesheet: '/shop/avatars_spritesheet.png', cols: 6, size: 512 },
};

export const BADGE_SPRITE_MAP: Record<string, SpriteInfo> = {
  '/shop/badges/champion.png': { index: 0, spritesheet: '/shop/badges_spritesheet.png', cols: 4, size: 256 },
  '/shop/badges/elite.png': { index: 1, spritesheet: '/shop/badges_spritesheet.png', cols: 4, size: 256 },
  '/shop/badges/legend.png': { index: 2, spritesheet: '/shop/badges_spritesheet.png', cols: 4, size: 256 },
  '/shop/badges/mythic.png': { index: 3, spritesheet: '/shop/badges_spritesheet.png', cols: 4, size: 256 },
  '/shop/badges/newcomer.png': { index: 4, spritesheet: '/shop/badges_spritesheet.png', cols: 4, size: 256 },
  '/shop/badges/nexus.png': { index: 5, spritesheet: '/shop/badges_spritesheet.png', cols: 4, size: 256 },
  '/shop/badges/vanguard.png': { index: 6, spritesheet: '/shop/badges_spritesheet.png', cols: 4, size: 256 },
  '/shop/badges/veteran.png': { index: 7, spritesheet: '/shop/badges_spritesheet.png', cols: 4, size: 256 },
};
