const fs = require('fs');
const path = require('path');
const sharp = require('sharp');

const AVATARS_DIR = path.resolve(
  __dirname,
  '../../apps/web/public/shop/avatars',
);
const BADGES_DIR = path.resolve(__dirname, '../../apps/web/public/shop/badges');

const OUT_AVATAR_SPRITE = path.resolve(
  __dirname,
  '../../apps/web/public/shop/avatars_spritesheet.webp',
);
const OUT_BADGE_SPRITE = path.resolve(
  __dirname,
  '../../apps/web/public/shop/badges_spritesheet.webp',
);

const OUT_TS_MAP = path.resolve(
  __dirname,
  '../../packages/ui/src/components/PlayerAvatar/sprite-maps.ts',
);

const AVATAR_SIZE = 128;
const AVATAR_COLS = 6;

const BADGE_SIZE = 96;
const BADGE_COLS = 4;

async function processCategory({ dir, cols, tileSize, outputPath, urlPrefix }) {
  if (!fs.existsSync(dir)) {
    console.error(`Directory does not exist: ${dir}`);
    return [];
  }

  const files = fs
    .readdirSync(dir)
    .filter((f) => f.endsWith('.png'))
    .sort((a, b) => a.localeCompare(b));

  const count = files.length;
  if (count === 0) {
    console.log(`No images found in ${dir}`);
    return [];
  }

  const rows = Math.ceil(count / cols);
  const sheetWidth = cols * tileSize;
  const sheetHeight = rows * tileSize;

  console.log(
    `Generating sheet: ${outputPath} (${sheetWidth}x${sheetHeight}), total ${count} items`,
  );

  const composites = [];
  const mappings = [];

  for (let i = 0; i < count; i++) {
    const file = files[i];
    const filePath = path.join(dir, file);
    const buffer = await sharp(filePath)
      .resize(tileSize, tileSize, { kernel: sharp.kernel.lanczos3 })
      .toBuffer();

    const col = i % cols;
    const row = Math.floor(i / cols);
    const x = col * tileSize;
    const y = row * tileSize;

    composites.push({
      input: buffer,
      top: y,
      left: x,
    });

    const publicUrl = `${urlPrefix}/${file}`;
    mappings.push({
      key: publicUrl,
      index: i,
    });
  }

  await sharp({
    create: {
      width: sheetWidth,
      height: sheetHeight,
      channels: 4,
      background: { r: 0, g: 0, b: 0, alpha: 0 },
    },
  })
    .composite(composites)
    .webp({ quality: 92, effort: 6, smartSubsample: true })
    .toFile(outputPath);

  console.log(`Successfully wrote ${outputPath}`);
  return mappings;
}

async function run() {
  console.log('Generating shop spritesheets...');

  const avatarMappings = await processCategory({
    dir: AVATARS_DIR,
    cols: AVATAR_COLS,
    tileSize: AVATAR_SIZE,
    outputPath: OUT_AVATAR_SPRITE,
    urlPrefix: '/shop/avatars',
  });

  const badgeMappings = await processCategory({
    dir: BADGES_DIR,
    cols: BADGE_COLS,
    tileSize: BADGE_SIZE,
    outputPath: OUT_BADGE_SPRITE,
    urlPrefix: '/shop/badges',
  });

  const tsContent = `// Automatically generated by scripts/spritesheet/generate_shop_spritesheets.js
// Do not edit directly.

import { resolveAssetUrl } from '../../utils/resolveAssetUrl';

export interface SpriteInfo {
  index: number;
  spritesheet: string;
  cols: number;
  size: number;
}

const _AVATAR_SPRITE_MAP: Record<string, Omit<SpriteInfo, 'spritesheet'>> = {
${avatarMappings.map((m) => `  '${m.key}': { index: ${m.index}, cols: ${AVATAR_COLS}, size: ${AVATAR_SIZE} },`).join('\n')}
};

const AVATAR_SPRITESHEET = resolveAssetUrl('/shop/avatars_spritesheet.webp');

export const AVATAR_SPRITE_MAP: Record<string, SpriteInfo> = Object.fromEntries(
  Object.entries(_AVATAR_SPRITE_MAP).map(([key, val]) => [
    key,
    { ...val, spritesheet: AVATAR_SPRITESHEET },
  ]),
);

const _BADGE_SPRITE_MAP: Record<string, Omit<SpriteInfo, 'spritesheet'>> = {
${badgeMappings.map((m) => `  '${m.key}': { index: ${m.index}, cols: ${BADGE_COLS}, size: ${BADGE_SIZE} },`).join('\n')}
};

const BADGE_SPRITESHEET = resolveAssetUrl('/shop/badges_spritesheet.webp');

export const BADGE_SPRITE_MAP: Record<string, SpriteInfo> = Object.fromEntries(
  Object.entries(_BADGE_SPRITE_MAP).map(([key, val]) => [
    key,
    { ...val, spritesheet: BADGE_SPRITESHEET },
  ]),
);
`;

  fs.writeFileSync(OUT_TS_MAP, tsContent, 'utf-8');
  console.log(`Wrote typescript map to ${OUT_TS_MAP}`);
}

run().catch(console.error);
