const fs = require('fs');
const path = require('path');
const Jimp = require('jimp');

const AVATARS_DIR = path.resolve(
  __dirname,
  '../../apps/web/public/shop/avatars',
);
const BADGES_DIR = path.resolve(__dirname, '../../apps/web/public/shop/badges');

const OUT_AVATAR_SPRITE = path.resolve(
  __dirname,
  '../../apps/web/public/shop/avatars_spritesheet.png',
);
const OUT_BADGE_SPRITE = path.resolve(
  __dirname,
  '../../apps/web/public/shop/badges_spritesheet.png',
);

const OUT_TS_MAP = path.resolve(
  __dirname,
  '../../packages/ui/src/components/PlayerAvatar/sprite-maps.ts',
);

const AVATAR_SIZE = 512;
const AVATAR_COLS = 6;

const BADGE_SIZE = 256;
const BADGE_COLS = 4;

async function processCategory({ dir, cols, tileSize, outputPath, urlPrefix }) {
  if (!fs.existsSync(dir)) {
    console.error(`Directory does not exist: ${dir}`);
    return [];
  }

  const files = fs
    .readdirSync(dir)
    .filter((f) => f.endsWith('.png'))
    .sort((a, b) => a.localeCompare(b));

  const count = files.length;
  if (count === 0) {
    console.log(`No images found in ${dir}`);
    return [];
  }

  const rows = Math.ceil(count / cols);
  const sheetWidth = cols * tileSize;
  const sheetHeight = rows * tileSize;

  console.log(
    `Generating sheet: ${outputPath} (${sheetWidth}x${sheetHeight}), total ${count} items`,
  );
  const sheet = new Jimp(sheetWidth, sheetHeight, 0x00000000);

  const mappings = [];

  for (let i = 0; i < count; i++) {
    const file = files[i];
    const filePath = path.join(dir, file);
    const img = await Jimp.read(filePath);
    img.resize(tileSize, tileSize);

    const col = i % cols;
    const row = Math.floor(i / cols);
    const x = col * tileSize;
    const y = row * tileSize;

    sheet.blit(img, x, y);

    const publicUrl = `${urlPrefix}/${file}`;
    mappings.push({
      key: publicUrl,
      index: i,
    });
  }

  await sheet.writeAsync(outputPath);
  console.log(`Successfully wrote ${outputPath}`);
  return mappings;
}

async function run() {
  console.log('Generating shop spritesheets...');

  const avatarMappings = await processCategory({
    dir: AVATARS_DIR,
    cols: AVATAR_COLS,
    tileSize: AVATAR_SIZE,
    outputPath: OUT_AVATAR_SPRITE,
    urlPrefix: '/shop/avatars',
  });

  const badgeMappings = await processCategory({
    dir: BADGES_DIR,
    cols: BADGE_COLS,
    tileSize: BADGE_SIZE,
    outputPath: OUT_BADGE_SPRITE,
    urlPrefix: '/shop/badges',
  });

  // Write TS map
  const tsContent = `// Automatically generated by scripts/spritesheet/generate_shop_spritesheets.js
// Do not edit directly.

export interface SpriteInfo {
  index: number;
  spritesheet: string;
  cols: number;
  size: number;
}

export const AVATAR_SPRITE_MAP: Record<string, SpriteInfo> = {
${avatarMappings.map((m) => `  '${m.key}': { index: ${m.index}, spritesheet: '/shop/avatars_spritesheet.png', cols: ${AVATAR_COLS}, size: ${AVATAR_SIZE} },`).join('\n')}
};

export const BADGE_SPRITE_MAP: Record<string, SpriteInfo> = {
${badgeMappings.map((m) => `  '${m.key}': { index: ${m.index}, spritesheet: '/shop/badges_spritesheet.png', cols: ${BADGE_COLS}, size: ${BADGE_SIZE} },`).join('\n')}
};
`;

  fs.writeFileSync(OUT_TS_MAP, tsContent, 'utf-8');
  console.log(`Wrote typescript map to ${OUT_TS_MAP}`);
}

run().catch(console.error);
