/** Moved to @arcadeum/games-core (ARC-900 offline mode). Re-export shim. */
export type {
  BoardPosition,
  ChessPiece,
  CastlingRights,
  ChessMove,
  ChessPlayer,
  ChessOptions,
  TimeControl,
  PlayerClock,
  LegalMove,
  ChessState,
  MovePayload,
  ChessEngineConfig,
  File,
  Rank,
  Board,
  TimeControlType,
  TimeIncrement,
} from '@arcadeum/games-core/games/chess/chess.types';
