import type { BlogPost } from '../../types';

export const post: BlogPost = {
  slug: 'chess-opening-traps',
  locale: 'en',
  title: '10 Chess Opening Traps Every Player Should Know',
  excerpt:
    "From the Scholar's Mate to the Fried Liver Attack — ten concrete opening traps with full move sequences, the ideas behind each, and how to avoid falling for them.",
  publishedAt: '2026-09-15',
  author: 'Arcadeum team',
  tags: ['Chess', 'Openings', 'Tactics', 'Strategy', 'Tutorial'],
  readingTimeMinutes: 10,
  body: [
    {
      type: 'paragraph',
      text: 'Opening traps are positions where one side can win material or deliver checkmate if the opponent plays natural-looking but incorrect moves. They are not the foundation of good chess — a well-prepared opponent sidesteps them easily — but knowing them helps in two ways: you will not fall into them yourself, and you will recognise when opponents blunder into positions you know cold. Here are ten traps you should learn and understand.',
    },
    {
      type: 'heading',
      level: 2,
      text: "1. Scholar's Mate — the four-move checkmate",
      id: 'scholars-mate',
    },
    {
      type: 'paragraph',
      text: 'The most famous trap in chess. White aims Qh5 and Bc4 at f7, the weakest square near the Black king.',
    },
    {
      type: 'chess-notation',
      title: "Scholar's Mate (White wins)",
      moves: ['e4', 'e5', 'Bc4', 'Nc6', 'Qh5', 'Nf6??', 'Qxf7#'],
      result: '1-0',
    },
    {
      type: 'paragraph',
      text: "The refutation is simple: after 3.Qh5, Black plays 3...g6 (attacking the queen), then develops normally. The queen retreats and White has wasted two moves. Never fear Scholar's Mate — greet it with g6 and enjoy the free tempo.",
    },
    {
      type: 'heading',
      level: 2,
      text: "2. Légal's Trap — the queen sacrifice",
      id: 'legal-trap',
    },
    {
      type: 'paragraph',
      text: 'One of the oldest traps. White sacrifices the queen to deliver a smothered-style mate with minor pieces.',
    },
    {
      type: 'chess-notation',
      title: "Légal's Trap",
      moves: [
        'e4',
        'e5',
        'Nf3',
        'Nc6',
        'Bc4',
        'd6',
        'Nc3',
        'Bg4',
        'Nxe5!',
        'Bxd1??',
        'Bxf7+',
        'Ke7',
        'Nd5#',
      ],
      result: '1-0',
    },
    {
      type: 'paragraph',
      text: 'After 8...Bg4, the pin looks threatening but is illusory. If Black takes the queen with 9...Bxd1, White plays Bxf7+, Nd5#. The correct defense is 9...Nxe5 or 9...dxe5, keeping the queen on the board.',
    },
    {
      type: 'heading',
      level: 2,
      text: "3. Fool's Mate — the two-move checkmate",
      id: 'fools-mate',
    },
    {
      type: 'paragraph',
      text: 'The fastest possible checkmate. White must play two terrible moves for it to work — but it is worth knowing.',
    },
    {
      type: 'chess-notation',
      title: "Fool's Mate (Black wins)",
      moves: ['f3??', 'e5', 'g4??', 'Qh4#'],
      result: '0-1',
    },
    {
      type: 'paragraph',
      text: "Only relevant if White plays both f3 and g4 — moves that open the diagonal and weaken the king. In practice, White never plays these in that order, but it illustrates why weakening the king's diagonal is catastrophic.",
    },
    {
      type: 'heading',
      level: 2,
      text: '4. The Fried Liver Attack',
      id: 'fried-liver',
    },
    {
      type: 'paragraph',
      text: 'A sacrificial gambit in the Two Knights Defense. White sacrifices a knight on f7 to expose the Black king.',
    },
    {
      type: 'chess-notation',
      title: 'Fried Liver Attack',
      moves: [
        'e4',
        'e5',
        'Nf3',
        'Nc6',
        'Bc4',
        'Nf6',
        'Ng5',
        'd5',
        'exd5',
        'Nxd5',
        'Nxf7!',
      ],
      result: '±',
    },
    {
      type: 'paragraph',
      text: 'After 7.Nxf7, Black must take with 7...Kxf7 — the king is dragged to the center. White plays 8.Qf3+ forcing 8...Ke6, then 9.Nc3 with massive pressure. This is not a forced win, but it leads to a highly complex, dangerous position that most Black players are not prepared for. The best defense is 6...h6 on move 6, preventing Ng5 entirely.',
    },
    {
      type: 'heading',
      level: 2,
      text: '5. The Budapest Gambit Trap',
      id: 'budapest',
    },
    {
      type: 'paragraph',
      text: 'Black offers a pawn on move two and sets a trap for the greedy White player who tries to hold material.',
    },
    {
      type: 'chess-notation',
      title: 'Budapest Gambit Trap',
      moves: [
        'd4',
        'Nf6',
        'c4',
        'e5',
        'dxe5',
        'Ng4',
        'Bf4',
        'Nc6',
        'Nf3',
        'Bb4+',
        'Nbd2',
        'Qe7',
        'e3',
        'Ngxe5',
        'Nxe5??',
        'Nxe5',
        'Be2',
        'Bxd2+',
        'Qxd2',
        'Nd3#',
      ],
      result: '0-1',
    },
    {
      type: 'paragraph',
      text: 'The queen, rook, and bishop all converge on d3 after the deflection. White should decline the gambit or play 9.e3 with careful development rather than grabbing the e5 pawn.',
    },
    {
      type: 'heading',
      level: 2,
      text: "6. The Elephant Trap (Queen's Gambit Declined)",
      id: 'elephant-trap',
    },
    {
      type: 'chess-notation',
      title: 'Elephant Trap',
      moves: [
        'd4',
        'd5',
        'c4',
        'e6',
        'Nc3',
        'Nf6',
        'Bg5',
        'Nbd7',
        'cxd5',
        'exd5',
        'Nxd5??',
        'Nxd5',
        'Bxd8??',
        'Bb4+',
        'Qd2',
        'Bxd2+',
        'Kxd2',
        'Kxd8',
      ],
      result: '∓',
    },
    {
      type: 'paragraph',
      text: 'White captures twice and apparently wins the queen, but after 7...Nxd5, 8.Bxd8?? runs into 8...Bb4+, winning back the queen and emerging a piece up. This is one of the most famous traps in classical openings. White should play 7.e3 or 7.Nf3 instead.',
    },
    {
      type: 'heading',
      level: 2,
      text: '7. The Stafford Gambit Trap',
      id: 'stafford',
    },
    {
      type: 'paragraph',
      text: 'A reversed Petrov where Black sacrifices a pawn for rapid development and traps the White queen.',
    },
    {
      type: 'chess-notation',
      title: 'Stafford Gambit — Queen Trap Line',
      moves: [
        'e4',
        'e5',
        'Nf3',
        'Nf6',
        'Nxe5',
        'Nc6',
        'Nxc6',
        'dxc6',
        'e5',
        'Ne4',
        'd3',
        'Bc5!',
        'dxe4??',
        'Bxf2+',
        'Ke2',
        'Bg4+',
        'Be2',
        'Bxe2',
        'Kxe2',
        'Qd2+',
        'Kf3',
        'Qf4#',
      ],
      result: '0-1',
    },
    {
      type: 'paragraph',
      text: 'The critical mistake is 7.dxe4, capturing the knight. After 7...Bxf2+, Black sacrifices both minor pieces for a mating net. The refutation is 7.Be3, exchanging the dangerous bishop before it reaches f2.',
    },
    {
      type: 'heading',
      level: 2,
      text: "8. The Noah's Ark Trap (Ruy López)",
      id: 'noahs-ark',
    },
    {
      type: 'paragraph',
      text: "One of the oldest recorded traps. White's bishop gets trapped on the queenside by Black pawns.",
    },
    {
      type: 'chess-notation',
      title: "Noah's Ark Trap",
      moves: [
        'e4',
        'e5',
        'Nf3',
        'Nc6',
        'Bb5',
        'a6',
        'Ba4',
        'd6',
        'O-O',
        'b5',
        'Bb3',
        'Na5',
        'Bc2?!',
        'c5',
        'Nxe5??',
        'd6-d5!',
        'Nf3',
        'd4',
        'Ne2',
        'c4',
      ],
      result: '∓',
    },
    {
      type: 'paragraph',
      text: "The bishop is buried alive on c2, completely boxed in by Black's pawn chain. In the Ruy López, White must be careful not to let c5-d4-c4 roll forward while the bishop is misplaced.",
    },
    {
      type: 'heading',
      level: 2,
      text: '9. The Fishing Pole Trap (Ruy López)',
      id: 'fishing-pole',
    },
    {
      type: 'chess-notation',
      title: 'Fishing Pole Trap',
      moves: [
        'e4',
        'e5',
        'Nf3',
        'Nc6',
        'Bb5',
        'Nf6',
        'O-O',
        'Ng4',
        'h3??',
        'h5!',
        'hxg4??',
        'hxg4',
        'Nxe5',
        'Qh4',
        'f4',
        'g3',
        'Nxc6',
        'dxc6',
        'Bxc6',
        'bxc6',
        'gxh1=Q',
      ],
      result: '0-1',
    },
    {
      type: 'paragraph',
      text: 'Black sacrifices the knight with 4...Ng4 and pushes h5 — the "fishing pole" that hooks the h-pawn. If White grabs 5.hxg4?? hxg4 and then captures on e5, the storm arrives via Qh4, g3, and the rook lifts. The correct response to Ng4 is 5.d4 or 5.Nc3, not h3.',
    },
    {
      type: 'heading',
      level: 2,
      text: '10. The Mortimer Trap (Ruy López)',
      id: 'mortimer',
    },
    {
      type: 'chess-notation',
      title: 'Mortimer Trap',
      moves: [
        'e4',
        'e5',
        'Nf3',
        'Nc6',
        'Bb5',
        'Nf6',
        'O-O',
        'Ne7!?',
        'Nxe5??',
        'c6!',
        'Nxf7??',
        'Qe8!',
        'Nxh8',
        'Qxe4',
      ],
      result: '∓',
    },
    {
      type: 'paragraph',
      text: "Black's surprising 4...Ne7 looks passive but sets a lethal trap. If White plays the natural 5.Nxe5??, Black replies 5...c6, attacking the bishop. After 6.Nxf7??, 6...Qe8! wins the knight with interest. White must play 5.Bxc6 instead.",
    },
    {
      type: 'heading',
      level: 2,
      text: 'Principles for avoiding traps yourself',
      id: 'avoiding-traps',
    },
    {
      type: 'list',
      items: [
        'Ask "why did they play that?" every single move. Unusual moves are often traps, not blunders.',
        'Be suspicious of pawn sacrifices. When your opponent offers a pawn in the opening with no obvious compensation, look for compensation that is not obvious.',
        "Don't grab material without calculating. Capturing with the wrong piece — or in the wrong order — is how most traps spring.",
        "Know your openings' critical moments. Every main opening has two or three squares where mistakes are punished immediately (f7 in Italian, d5 in Budapest). Know them.",
        'When ahead in material, simplify. Traps thrive in complex positions where your calculations are stressed. Trade pieces and the complications disappear.',
      ],
    },
    {
      type: 'cta',
      href: '/games/chess',
      text: 'Test your trap knowledge — play Chess on Arcadeum',
      description:
        'Practice these openings in real games. Use the post-game analysis to see exactly where the critical moments arose.',
    },
    {
      type: 'heading',
      level: 2,
      text: "TL;DR — the trapper's checklist",
      id: 'tldr',
    },
    {
      type: 'list',
      items: [
        "Scholar's Mate → counter with g6 on move 3.",
        'Légal\'s Trap → don\'t take the "free" queen; play Nxe5 instead.',
        'Fried Liver → prevent with h6 on move 6 before Ng5.',
        'Stafford Gambit → answer Bc5 with Be3, not dxe4.',
        'Always ask why before capturing — the most expensive pieces in chess are the ones you take for free.',
      ],
    },
  ],
  faq: [
    {
      question: 'Can I use these traps in serious games?',
      answer:
        'Yes, but only as secondary weapons. Traps work on opponents who are unprepared or in time trouble. Experienced players know the refutations, so your main preparation should still be sound opening principles.',
    },
    {
      question: 'Which trap is easiest to learn first?',
      answer:
        "Scholar's Mate — not because it wins games, but because knowing it and its refutation teaches you the concept of king safety and tempo simultaneously.",
    },
    {
      question: 'What if my opponent avoids the trap?',
      answer:
        'Good traps leave you with a playable or equal position even if the opponent sidesteps correctly. Avoid traps that leave you with a losing position when the opponent finds the right move.',
    },
    {
      question: 'Is memorizing traps better than learning endgames?',
      answer:
        'No. Endgame knowledge converts advantages; opening traps only work against mistakes. Invest most of your study time in tactics (puzzles) and endgames — traps are a small complement, not the main course.',
    },
  ],
  howTo: {
    totalTime: 'PT15M',
    steps: [
      {
        name: 'Recognise the trap pattern',
        text: 'Each trap has a signature: a sacrifice, an unusual retreat, or a pawn push. Learn the key move in each trap — that is the one to spot.',
        url: '#scholars-mate',
      },
      {
        name: 'Ask "why?" before capturing',
        text: 'Most traps spring when a player captures without calculating to the end. Before taking any piece, ask whether there is a hidden counter.',
        url: '#avoiding-traps',
      },
      {
        name: 'Know the refutations',
        text: 'Memorising the refutation for each trap is as important as knowing the trap itself — it teaches you what your opponent should have done.',
        url: '#avoiding-traps',
      },
    ],
  },
};
