import type { ShopItemDef } from './shop-types';

/**
 * Color cosmetics — name colors, banners, auras, and frames. These use
 * `colorValue` (solid hex or linear-gradient) instead of an image asset.
 * Kept in a sibling module so the main `shop-catalog.ts` stays under the
 * file-length limit.
 */
export const SHOP_COSMETIC_ITEMS: Record<string, ShopItemDef> = {
  // Name colors — color swatch rendered via `colorValue`.
  'name-color-default': {
    id: 'name-color-default',
    category: 'name_color',
    rarity: 'common',
    nameKey: 'items.name_color.default.name',
    descKey: 'items.name_color.default.desc',
    assetUrl: '',
    colorValue: '#e2e8f0',
    defaultPriceAmount: 0,
    defaultPriceCurrency: 'coins',
    starter: true,
  },
  'name-color-slate': {
    id: 'name-color-slate',
    category: 'name_color',
    rarity: 'common',
    nameKey: 'items.name_color.slate.name',
    descKey: 'items.name_color.slate.desc',
    assetUrl: '',
    colorValue: '#94a3b8',
    defaultPriceAmount: 200,
    defaultPriceCurrency: 'coins',
  },
  'name-color-emerald': {
    id: 'name-color-emerald',
    category: 'name_color',
    rarity: 'common',
    nameKey: 'items.name_color.emerald.name',
    descKey: 'items.name_color.emerald.desc',
    assetUrl: '',
    colorValue: '#34d399',
    defaultPriceAmount: 300,
    defaultPriceCurrency: 'coins',
  },
  'name-color-cyan': {
    id: 'name-color-cyan',
    category: 'name_color',
    rarity: 'rare',
    nameKey: 'items.name_color.cyan.name',
    descKey: 'items.name_color.cyan.desc',
    assetUrl: '',
    colorValue: '#22d3ee',
    defaultPriceAmount: 2,
    defaultPriceCurrency: 'gems',
  },
  'name-color-violet': {
    id: 'name-color-violet',
    category: 'name_color',
    rarity: 'rare',
    nameKey: 'items.name_color.violet.name',
    descKey: 'items.name_color.violet.desc',
    assetUrl: '',
    colorValue: '#a78bfa',
    defaultPriceAmount: 3,
    defaultPriceCurrency: 'gems',
  },
  'name-color-sunset': {
    id: 'name-color-sunset',
    category: 'name_color',
    rarity: 'epic',
    nameKey: 'items.name_color.sunset.name',
    descKey: 'items.name_color.sunset.desc',
    assetUrl: '',
    colorValue: 'linear-gradient(90deg, #f97316 0%, #ec4899 100%)',
    defaultPriceAmount: 12,
    defaultPriceCurrency: 'gems',
  },
  'name-color-aurora': {
    id: 'name-color-aurora',
    category: 'name_color',
    rarity: 'legendary',
    nameKey: 'items.name_color.aurora.name',
    descKey: 'items.name_color.aurora.desc',
    assetUrl: '',
    colorValue: 'linear-gradient(90deg, #22d3ee 0%, #a78bfa 50%, #ec4899 100%)',
    defaultPriceAmount: 40,
    defaultPriceCurrency: 'gems',
  },
  'name-color-nebula': {
    id: 'name-color-nebula',
    category: 'name_color',
    rarity: 'legendary',
    nameKey: 'items.name_color.nebula.name',
    descKey: 'items.name_color.nebula.desc',
    assetUrl: '',
    colorValue: 'linear-gradient(90deg, #818cf8 0%, #c084fc 50%, #f472b6 100%)',
    defaultPriceAmount: 30,
    defaultPriceCurrency: 'gems',
  },
  'name-color-glitch': {
    id: 'name-color-glitch',
    category: 'name_color',
    rarity: 'epic',
    nameKey: 'items.name_color.glitch.name',
    descKey: 'items.name_color.glitch.desc',
    assetUrl: '',
    colorValue: 'linear-gradient(90deg, #f43f5e 0%, #06b6d4 100%)',
    defaultPriceAmount: 15,
    defaultPriceCurrency: 'gems',
  },

  // Banners — backdrop panel behind the avatar. `colorValue` is a solid
  // hex or linear-gradient; ItemAsset renders a wide gradient tile.
  'banner-default': {
    id: 'banner-default',
    category: 'banner',
    rarity: 'common',
    nameKey: 'items.banner.default.name',
    descKey: 'items.banner.default.desc',
    assetUrl: '',
    colorValue: '#0f172a',
    defaultPriceAmount: 0,
    defaultPriceCurrency: 'coins',
    starter: true,
  },
  'banner-slate': {
    id: 'banner-slate',
    category: 'banner',
    rarity: 'common',
    nameKey: 'items.banner.slate.name',
    descKey: 'items.banner.slate.desc',
    assetUrl: '',
    colorValue: 'linear-gradient(135deg, #1e293b 0%, #334155 100%)',
    defaultPriceAmount: 250,
    defaultPriceCurrency: 'coins',
  },
  'banner-tide': {
    id: 'banner-tide',
    category: 'banner',
    rarity: 'rare',
    nameKey: 'items.banner.tide.name',
    descKey: 'items.banner.tide.desc',
    assetUrl: '',
    colorValue: 'linear-gradient(135deg, #0ea5e9 0%, #14b8a6 100%)',
    defaultPriceAmount: 3,
    defaultPriceCurrency: 'gems',
  },
  'banner-twilight': {
    id: 'banner-twilight',
    category: 'banner',
    rarity: 'epic',
    nameKey: 'items.banner.twilight.name',
    descKey: 'items.banner.twilight.desc',
    assetUrl: '',
    colorValue: 'linear-gradient(135deg, #6366f1 0%, #ec4899 100%)',
    defaultPriceAmount: 12,
    defaultPriceCurrency: 'gems',
  },
  'banner-nebula': {
    id: 'banner-nebula',
    category: 'banner',
    rarity: 'legendary',
    nameKey: 'items.banner.nebula.name',
    descKey: 'items.banner.nebula.desc',
    assetUrl: '',
    colorValue:
      'linear-gradient(135deg, #1e1b4b 0%, #6366f1 35%, #ec4899 70%, #f59e0b 100%)',
    defaultPriceAmount: 45,
    defaultPriceCurrency: 'gems',
  },
  'banner-cyberpunk': {
    id: 'banner-cyberpunk',
    category: 'banner',
    rarity: 'epic',
    nameKey: 'items.banner.cyberpunk.name',
    descKey: 'items.banner.cyberpunk.desc',
    assetUrl: '',
    colorValue:
      'linear-gradient(135deg, #0f172a 0%, #f43f5e 50%, #eab308 100%)',
    defaultPriceAmount: 15,
    defaultPriceCurrency: 'gems',
  },
  'banner-void': {
    id: 'banner-void',
    category: 'banner',
    rarity: 'legendary',
    nameKey: 'items.banner.void.name',
    descKey: 'items.banner.void.desc',
    assetUrl: '',
    colorValue:
      'linear-gradient(135deg, #030712 0%, #111827 50%, #312e81 100%)',
    defaultPriceAmount: 40,
    defaultPriceCurrency: 'gems',
  },

  // Auras — animated glow around the player's name.
  'aura-default': {
    id: 'aura-default',
    category: 'aura',
    rarity: 'common',
    nameKey: 'items.aura.default.name',
    descKey: 'items.aura.default.desc',
    assetUrl: '',
    colorValue: '#94a3b8',
    defaultPriceAmount: 0,
    defaultPriceCurrency: 'coins',
    starter: true,
  },
  'aura-silver': {
    id: 'aura-silver',
    category: 'aura',
    rarity: 'common',
    nameKey: 'items.aura.silver.name',
    descKey: 'items.aura.silver.desc',
    assetUrl: '',
    colorValue: '#cbd5e1',
    defaultPriceAmount: 350,
    defaultPriceCurrency: 'coins',
  },
  'aura-cyan': {
    id: 'aura-cyan',
    category: 'aura',
    rarity: 'rare',
    nameKey: 'items.aura.cyan.name',
    descKey: 'items.aura.cyan.desc',
    assetUrl: '',
    colorValue: '#22d3ee',
    defaultPriceAmount: 4,
    defaultPriceCurrency: 'gems',
  },
  'aura-violet': {
    id: 'aura-violet',
    category: 'aura',
    rarity: 'epic',
    nameKey: 'items.aura.violet.name',
    descKey: 'items.aura.violet.desc',
    assetUrl: '',
    colorValue: '#a78bfa',
    defaultPriceAmount: 14,
    defaultPriceCurrency: 'gems',
  },
  'aura-prism': {
    id: 'aura-prism',
    category: 'aura',
    rarity: 'legendary',
    nameKey: 'items.aura.prism.name',
    descKey: 'items.aura.prism.desc',
    assetUrl: '',
    colorValue: 'linear-gradient(90deg, #22d3ee 0%, #a78bfa 50%, #ec4899 100%)',
    defaultPriceAmount: 55,
    defaultPriceCurrency: 'gems',
  },
  'aura-gold': {
    id: 'aura-gold',
    category: 'aura',
    rarity: 'epic',
    nameKey: 'items.aura.gold.name',
    descKey: 'items.aura.gold.desc',
    assetUrl: '',
    colorValue: '#f59e0b',
    defaultPriceAmount: 18,
    defaultPriceCurrency: 'gems',
  },
  'aura-glitch': {
    id: 'aura-glitch',
    category: 'aura',
    rarity: 'legendary',
    nameKey: 'items.aura.glitch.name',
    descKey: 'items.aura.glitch.desc',
    assetUrl: '',
    colorValue: 'linear-gradient(90deg, #ef4444 0%, #06b6d4 100%)',
    defaultPriceAmount: 45,
    defaultPriceCurrency: 'gems',
  },

  // Frames — decorative ring around the avatar disc.
  'frame-default': {
    id: 'frame-default',
    category: 'frame',
    rarity: 'common',
    nameKey: 'items.frame.default.name',
    descKey: 'items.frame.default.desc',
    assetUrl: '',
    colorValue: '#475569',
    defaultPriceAmount: 0,
    defaultPriceCurrency: 'coins',
    starter: true,
  },
  'frame-silver': {
    id: 'frame-silver',
    category: 'frame',
    rarity: 'common',
    nameKey: 'items.frame.silver.name',
    descKey: 'items.frame.silver.desc',
    assetUrl: '',
    colorValue: '#94a3b8',
    defaultPriceAmount: 300,
    defaultPriceCurrency: 'coins',
  },
  'frame-emerald': {
    id: 'frame-emerald',
    category: 'frame',
    rarity: 'rare',
    nameKey: 'items.frame.emerald.name',
    descKey: 'items.frame.emerald.desc',
    assetUrl: '',
    colorValue: '#10b981',
    defaultPriceAmount: 3,
    defaultPriceCurrency: 'gems',
  },
  'frame-violet': {
    id: 'frame-violet',
    category: 'frame',
    rarity: 'epic',
    nameKey: 'items.frame.violet.name',
    descKey: 'items.frame.violet.desc',
    assetUrl: '',
    colorValue: '#a78bfa',
    defaultPriceAmount: 12,
    defaultPriceCurrency: 'gems',
  },
  'frame-prism': {
    id: 'frame-prism',
    category: 'frame',
    rarity: 'legendary',
    nameKey: 'items.frame.prism.name',
    descKey: 'items.frame.prism.desc',
    assetUrl: '',
    colorValue:
      'linear-gradient(135deg, #22d3ee 0%, #a78bfa 50%, #ec4899 100%)',
    defaultPriceAmount: 50,
    defaultPriceCurrency: 'gems',
  },
  'frame-gold': {
    id: 'frame-gold',
    category: 'frame',
    rarity: 'epic',
    nameKey: 'items.frame.gold.name',
    descKey: 'items.frame.gold.desc',
    assetUrl: '',
    colorValue: '#eab308',
    defaultPriceAmount: 15,
    defaultPriceCurrency: 'gems',
  },
  'frame-cyberpunk': {
    id: 'frame-cyberpunk',
    category: 'frame',
    rarity: 'legendary',
    nameKey: 'items.frame.cyberpunk.name',
    descKey: 'items.frame.cyberpunk.desc',
    assetUrl: '',
    colorValue:
      'linear-gradient(135deg, #ec4899 0%, #f43f5e 50%, #06b6d4 100%)',
    defaultPriceAmount: 48,
    defaultPriceCurrency: 'gems',
  },
};
