import type { ShopItemDef } from './shop-types';

export const AURAS: Record<string, ShopItemDef> = {
  'aura-default': {
    id: 'aura-default',
    category: 'aura',
    rarity: 'common',
    nameKey: 'items.aura.default.name',
    descKey: 'items.aura.default.desc',
    assetUrl: '',
    colorValue: '#94a3b8',
    defaultPriceAmount: 0,
    defaultPriceCurrency: 'coins',
    starter: true,
  },
  'aura-silver': {
    id: 'aura-silver',
    category: 'aura',
    rarity: 'common',
    nameKey: 'items.aura.silver.name',
    descKey: 'items.aura.silver.desc',
    assetUrl: '',
    colorValue: '#cbd5e1',
    defaultPriceAmount: 350,
    defaultPriceCurrency: 'coins',
  },
  'aura-cyan': {
    id: 'aura-cyan',
    category: 'aura',
    rarity: 'rare',
    nameKey: 'items.aura.cyan.name',
    descKey: 'items.aura.cyan.desc',
    assetUrl: '',
    colorValue: '#22d3ee',
    defaultPriceAmount: 4,
    defaultPriceCurrency: 'gems',
  },
  'aura-violet': {
    id: 'aura-violet',
    category: 'aura',
    rarity: 'epic',
    nameKey: 'items.aura.violet.name',
    descKey: 'items.aura.violet.desc',
    assetUrl: '',
    colorValue: '#a78bfa',
    defaultPriceAmount: 14,
    defaultPriceCurrency: 'gems',
  },
  'aura-prism': {
    id: 'aura-prism',
    category: 'aura',
    rarity: 'legendary',
    nameKey: 'items.aura.prism.name',
    descKey: 'items.aura.prism.desc',
    assetUrl: '',
    colorValue: 'linear-gradient(90deg, #22d3ee 0%, #a78bfa 50%, #ec4899 100%)',
    defaultPriceAmount: 55,
    defaultPriceCurrency: 'gems',
  },
  'aura-gold': {
    id: 'aura-gold',
    category: 'aura',
    rarity: 'epic',
    nameKey: 'items.aura.gold.name',
    descKey: 'items.aura.gold.desc',
    assetUrl: '',
    colorValue: '#f59e0b',
    defaultPriceAmount: 18,
    defaultPriceCurrency: 'gems',
  },
  'aura-glitch': {
    id: 'aura-glitch',
    category: 'aura',
    rarity: 'legendary',
    nameKey: 'items.aura.glitch.name',
    descKey: 'items.aura.glitch.desc',
    assetUrl: '',
    colorValue: 'linear-gradient(90deg, #ef4444 0%, #06b6d4 100%)',
    defaultPriceAmount: 45,
    defaultPriceCurrency: 'gems',
  },
  'aura-neon': {
    id: 'aura-neon',
    category: 'aura',
    rarity: 'epic',
    nameKey: 'items.aura.neon.name',
    descKey: 'items.aura.neon.desc',
    assetUrl: '',
    colorValue: '#39ff14',
    defaultPriceAmount: 20,
    defaultPriceCurrency: 'gems',
  },
  'aura-solar': {
    id: 'aura-solar',
    category: 'aura',
    rarity: 'epic',
    nameKey: 'items.aura.solar.name',
    descKey: 'items.aura.solar.desc',
    assetUrl: '',
    colorValue: '#ff4500',
    defaultPriceAmount: 20,
    defaultPriceCurrency: 'gems',
  },
  'aura-magma': {
    id: 'aura-magma',
    category: 'aura',
    rarity: 'legendary',
    nameKey: 'items.aura.magma.name',
    descKey: 'items.aura.magma.desc',
    assetUrl: '',
    colorValue: '#ff0000',
    defaultPriceAmount: 25,
    defaultPriceCurrency: 'gems',
  },
  'aura-oceanic': {
    id: 'aura-oceanic',
    category: 'aura',
    rarity: 'epic',
    nameKey: 'items.aura.oceanic.name',
    descKey: 'items.aura.oceanic.desc',
    assetUrl: '',
    colorValue: '#00ced1',
    defaultPriceAmount: 22,
    defaultPriceCurrency: 'gems',
  },
  'aura-sakura': {
    id: 'aura-sakura',
    category: 'aura',
    rarity: 'epic',
    nameKey: 'items.aura.sakura.name',
    descKey: 'items.aura.sakura.desc',
    assetUrl: '',
    colorValue: '#ff69b4',
    defaultPriceAmount: 18,
    defaultPriceCurrency: 'gems',
  },
  'aura-void': {
    id: 'aura-void',
    category: 'aura',
    rarity: 'legendary',
    nameKey: 'items.aura.void.name',
    descKey: 'items.aura.void.desc',
    assetUrl: '',
    colorValue: '#4b0082',
    defaultPriceAmount: 25,
    defaultPriceCurrency: 'gems',
  },
};
