import type { ShopItemDef } from './shop-types';

export const NAME_COLORS: Record<string, ShopItemDef> = {
  'name-color-default': {
    id: 'name-color-default',
    category: 'name_color',
    rarity: 'common',
    nameKey: 'items.name_color.default.name',
    descKey: 'items.name_color.default.desc',
    assetUrl: '',
    colorValue: '#e2e8f0',
    defaultPriceAmount: 0,
    defaultPriceCurrency: 'coins',
    starter: true,
  },
  'name-color-slate': {
    id: 'name-color-slate',
    category: 'name_color',
    rarity: 'common',
    nameKey: 'items.name_color.slate.name',
    descKey: 'items.name_color.slate.desc',
    assetUrl: '',
    colorValue: '#94a3b8',
    defaultPriceAmount: 200,
    defaultPriceCurrency: 'coins',
  },
  'name-color-emerald': {
    id: 'name-color-emerald',
    category: 'name_color',
    rarity: 'common',
    nameKey: 'items.name_color.emerald.name',
    descKey: 'items.name_color.emerald.desc',
    assetUrl: '',
    colorValue: '#34d399',
    defaultPriceAmount: 300,
    defaultPriceCurrency: 'coins',
  },
  'name-color-cyan': {
    id: 'name-color-cyan',
    category: 'name_color',
    rarity: 'rare',
    nameKey: 'items.name_color.cyan.name',
    descKey: 'items.name_color.cyan.desc',
    assetUrl: '',
    colorValue: '#22d3ee',
    defaultPriceAmount: 2,
    defaultPriceCurrency: 'gems',
  },
  'name-color-violet': {
    id: 'name-color-violet',
    category: 'name_color',
    rarity: 'rare',
    nameKey: 'items.name_color.violet.name',
    descKey: 'items.name_color.violet.desc',
    assetUrl: '',
    colorValue: '#a78bfa',
    defaultPriceAmount: 3,
    defaultPriceCurrency: 'gems',
  },
  'name-color-sunset': {
    id: 'name-color-sunset',
    category: 'name_color',
    rarity: 'epic',
    nameKey: 'items.name_color.sunset.name',
    descKey: 'items.name_color.sunset.desc',
    assetUrl: '',
    colorValue: 'linear-gradient(90deg, #f97316 0%, #ec4899 100%)',
    defaultPriceAmount: 12,
    defaultPriceCurrency: 'gems',
  },
  'name-color-aurora': {
    id: 'name-color-aurora',
    category: 'name_color',
    rarity: 'legendary',
    nameKey: 'items.name_color.aurora.name',
    descKey: 'items.name_color.aurora.desc',
    assetUrl: '',
    colorValue: 'linear-gradient(90deg, #22d3ee 0%, #a78bfa 50%, #ec4899 100%)',
    defaultPriceAmount: 40,
    defaultPriceCurrency: 'gems',
  },
  'name-color-nebula': {
    id: 'name-color-nebula',
    category: 'name_color',
    rarity: 'legendary',
    nameKey: 'items.name_color.nebula.name',
    descKey: 'items.name_color.nebula.desc',
    assetUrl: '',
    colorValue: 'linear-gradient(90deg, #818cf8 0%, #c084fc 50%, #f472b6 100%)',
    defaultPriceAmount: 30,
    defaultPriceCurrency: 'gems',
  },
  'name-color-glitch': {
    id: 'name-color-glitch',
    category: 'name_color',
    rarity: 'epic',
    nameKey: 'items.name_color.glitch.name',
    descKey: 'items.name_color.glitch.desc',
    assetUrl: '',
    colorValue: 'linear-gradient(90deg, #f43f5e 0%, #06b6d4 100%)',
    defaultPriceAmount: 15,
    defaultPriceCurrency: 'gems',
  },
  'name-color-neon': {
    id: 'name-color-neon',
    category: 'name_color',
    rarity: 'epic',
    nameKey: 'items.name_color.neon.name',
    descKey: 'items.name_color.neon.desc',
    assetUrl: '',
    colorValue: 'linear-gradient(90deg, #39ff14 0%, #00ffff 100%)',
    defaultPriceAmount: 15,
    defaultPriceCurrency: 'gems',
  },
  'name-color-solar': {
    id: 'name-color-solar',
    category: 'name_color',
    rarity: 'rare',
    nameKey: 'items.name_color.solar.name',
    descKey: 'items.name_color.solar.desc',
    assetUrl: '',
    colorValue: 'linear-gradient(90deg, #ff4500 0%, #ff8c00 100%)',
    defaultPriceAmount: 5,
    defaultPriceCurrency: 'gems',
  },
  'name-color-magma': {
    id: 'name-color-magma',
    category: 'name_color',
    rarity: 'epic',
    nameKey: 'items.name_color.magma.name',
    descKey: 'items.name_color.magma.desc',
    assetUrl: '',
    colorValue: 'linear-gradient(90deg, #ff0000 0%, #ff4500 50%, #ff8c00 100%)',
    defaultPriceAmount: 20,
    defaultPriceCurrency: 'gems',
  },
  'name-color-oceanic': {
    id: 'name-color-oceanic',
    category: 'name_color',
    rarity: 'epic',
    nameKey: 'items.name_color.oceanic.name',
    descKey: 'items.name_color.oceanic.desc',
    assetUrl: '',
    colorValue: 'linear-gradient(90deg, #00ced1 0%, #1e90ff 50%, #0000ff 100%)',
    defaultPriceAmount: 20,
    defaultPriceCurrency: 'gems',
  },
  'name-color-forest': {
    id: 'name-color-forest',
    category: 'name_color',
    rarity: 'rare',
    nameKey: 'items.name_color.forest.name',
    descKey: 'items.name_color.forest.desc',
    assetUrl: '',
    colorValue: 'linear-gradient(90deg, #00ff00 0%, #008000 50%, #006400 100%)',
    defaultPriceAmount: 12,
    defaultPriceCurrency: 'gems',
  },
  'name-color-prismatic': {
    id: 'name-color-prismatic',
    category: 'name_color',
    rarity: 'legendary',
    nameKey: 'items.name_color.prismatic.name',
    descKey: 'items.name_color.prismatic.desc',
    assetUrl: '',
    colorValue: 'linear-gradient(90deg, #ff00ff 0%, #00ffff 50%, #ffff00 100%)',
    defaultPriceAmount: 35,
    defaultPriceCurrency: 'gems',
  },
  'name-color-void-cosmetic': {
    id: 'name-color-void-cosmetic',
    category: 'name_color',
    rarity: 'legendary',
    nameKey: 'items.name_color.void.name',
    descKey: 'items.name_color.void.desc',
    assetUrl: '',
    colorValue: 'linear-gradient(90deg, #000000 0%, #4b0082 100%)',
    defaultPriceAmount: 25,
    defaultPriceCurrency: 'gems',
  },
  'name-color-sakura': {
    id: 'name-color-sakura',
    category: 'name_color',
    rarity: 'epic',
    nameKey: 'items.name_color.sakura.name',
    descKey: 'items.name_color.sakura.desc',
    assetUrl: '',
    colorValue: 'linear-gradient(90deg, #ffb7c5 0%, #ffc0cb 50%, #ff69b4 100%)',
    defaultPriceAmount: 18,
    defaultPriceCurrency: 'gems',
  },
  'name-color-gold-cosmetic': {
    id: 'name-color-gold-cosmetic',
    category: 'name_color',
    rarity: 'legendary',
    nameKey: 'items.name_color.gold.name',
    descKey: 'items.name_color.gold.desc',
    assetUrl: '',
    colorValue: 'linear-gradient(90deg, #ffd700 0%, #ffa500 100%)',
    defaultPriceAmount: 25,
    defaultPriceCurrency: 'gems',
  },
  'name-color-supernova': {
    id: 'name-color-supernova',
    category: 'name_color',
    rarity: 'legendary',
    nameKey: 'items.name_color.supernova.name',
    descKey: 'items.name_color.supernova.desc',
    assetUrl: '',
    colorValue: 'linear-gradient(90deg, #ff007f 0%, #ffaa00 50%, #00ffff 100%)',
    defaultPriceAmount: 30,
    defaultPriceCurrency: 'gems',
  },
  'name-color-synthwave': {
    id: 'name-color-synthwave',
    category: 'name_color',
    rarity: 'epic',
    nameKey: 'items.name_color.synthwave.name',
    descKey: 'items.name_color.synthwave.desc',
    assetUrl: '',
    colorValue: 'linear-gradient(90deg, #ff00a0 0%, #ff00ff 50%, #00ffff 100%)',
    defaultPriceAmount: 20,
    defaultPriceCurrency: 'gems',
  },
};
