import type { ShopItemDef } from './shop-types';

/**
 * Avatar disc backgrounds — the radial wash painted behind the avatar art,
 * inside the frame ring. `colorValue` is a solid hex or a linear-gradient,
 * matching the aura/frame/banner convention. Kept in a sibling module so the
 * main `shop-catalog.ts` stays under the file-length limit.
 */
export const SHOP_BACKGROUND_ITEMS: Record<string, ShopItemDef> = {
  'background-default': {
    id: 'background-default',
    category: 'background',
    rarity: 'common',
    nameKey: 'items.background.default.name',
    descKey: 'items.background.default.desc',
    assetUrl: '',
    colorValue: '#1e293b',
    defaultPriceAmount: 0,
    defaultPriceCurrency: 'coins',
    starter: true,
  },
  'background-slate': {
    id: 'background-slate',
    category: 'background',
    rarity: 'common',
    nameKey: 'items.background.slate.name',
    descKey: 'items.background.slate.desc',
    assetUrl: '',
    colorValue: '#334155',
    defaultPriceAmount: 300,
    defaultPriceCurrency: 'coins',
  },
  'background-ocean': {
    id: 'background-ocean',
    category: 'background',
    rarity: 'rare',
    nameKey: 'items.background.ocean.name',
    descKey: 'items.background.ocean.desc',
    assetUrl: '',
    colorValue: 'linear-gradient(135deg, #0e7490 0%, #1e3a8a 100%)',
    defaultPriceAmount: 4,
    defaultPriceCurrency: 'gems',
  },
  'background-violet': {
    id: 'background-violet',
    category: 'background',
    rarity: 'epic',
    nameKey: 'items.background.violet.name',
    descKey: 'items.background.violet.desc',
    assetUrl: '',
    colorValue: 'linear-gradient(135deg, #4c1d95 0%, #7c3aed 100%)',
    defaultPriceAmount: 14,
    defaultPriceCurrency: 'gems',
  },
  'background-aurora': {
    id: 'background-aurora',
    category: 'background',
    rarity: 'legendary',
    nameKey: 'items.background.aurora.name',
    descKey: 'items.background.aurora.desc',
    assetUrl: '',
    colorValue:
      'linear-gradient(135deg, #0e7490 0%, #7c3aed 50%, #db2777 100%)',
    defaultPriceAmount: 50,
    defaultPriceCurrency: 'gems',
  },
  'background-neon': {
    id: 'background-neon',
    category: 'background',
    rarity: 'epic',
    nameKey: 'items.background.neon.name',
    descKey: 'items.background.neon.desc',
    assetUrl: '',
    colorValue: 'linear-gradient(135deg, #39ff14 0%, #00ffff 100%)',
    defaultPriceAmount: 15,
    defaultPriceCurrency: 'gems',
  },
  'background-magma': {
    id: 'background-magma',
    category: 'background',
    rarity: 'epic',
    nameKey: 'items.background.magma.name',
    descKey: 'items.background.magma.desc',
    assetUrl: '',
    colorValue: 'linear-gradient(135deg, #ff0000 0%, #ff8c00 100%)',
    defaultPriceAmount: 18,
    defaultPriceCurrency: 'gems',
  },
  'background-sunset': {
    id: 'background-sunset',
    category: 'background',
    rarity: 'rare',
    nameKey: 'items.background.sunset.name',
    descKey: 'items.background.sunset.desc',
    assetUrl: '',
    colorValue: 'linear-gradient(135deg, #f97316 0%, #ec4899 100%)',
    defaultPriceAmount: 6,
    defaultPriceCurrency: 'gems',
  },
  'background-cyberpunk': {
    id: 'background-cyberpunk',
    category: 'background',
    rarity: 'legendary',
    nameKey: 'items.background.cyberpunk.name',
    descKey: 'items.background.cyberpunk.desc',
    assetUrl: '',
    colorValue: 'linear-gradient(135deg, #ff00a0 0%, #00ffff 100%)',
    defaultPriceAmount: 35,
    defaultPriceCurrency: 'gems',
  },
  'background-void': {
    id: 'background-void',
    category: 'background',
    rarity: 'legendary',
    nameKey: 'items.background.void.name',
    descKey: 'items.background.void.desc',
    assetUrl: '',
    colorValue: 'linear-gradient(135deg, #000000 0%, #4b0082 100%)',
    defaultPriceAmount: 25,
    defaultPriceCurrency: 'gems',
  },
  'background-sakura': {
    id: 'background-sakura',
    category: 'background',
    rarity: 'epic',
    nameKey: 'items.background.sakura.name',
    descKey: 'items.background.sakura.desc',
    assetUrl: '',
    colorValue: 'linear-gradient(135deg, #ffb7c5 0%, #ff69b4 100%)',
    defaultPriceAmount: 14,
    defaultPriceCurrency: 'gems',
  },
  'background-gold': {
    id: 'background-gold',
    category: 'background',
    rarity: 'legendary',
    nameKey: 'items.background.gold.name',
    descKey: 'items.background.gold.desc',
    assetUrl: '',
    colorValue: 'linear-gradient(135deg, #ffd700 0%, #ffa500 100%)',
    defaultPriceAmount: 30,
    defaultPriceCurrency: 'gems',
  },
  'background-synthwave': {
    id: 'background-synthwave',
    category: 'background',
    rarity: 'epic',
    nameKey: 'items.background.synthwave.name',
    descKey: 'items.background.synthwave.desc',
    assetUrl: '',
    colorValue: 'linear-gradient(135deg, #ff007f 0%, #00ffff 100%)',
    defaultPriceAmount: 16,
    defaultPriceCurrency: 'gems',
  },
};
