import type { ShopItemDef } from './shop-types';

export const FRAMES: Record<string, ShopItemDef> = {
  'frame-default': {
    id: 'frame-default',
    category: 'frame',
    rarity: 'common',
    nameKey: 'items.frame.default.name',
    descKey: 'items.frame.default.desc',
    assetUrl: '',
    colorValue: '#475569',
    defaultPriceAmount: 0,
    defaultPriceCurrency: 'coins',
    starter: true,
  },
  'frame-silver': {
    id: 'frame-silver',
    category: 'frame',
    rarity: 'common',
    nameKey: 'items.frame.silver.name',
    descKey: 'items.frame.silver.desc',
    assetUrl: '',
    colorValue: '#94a3b8',
    defaultPriceAmount: 300,
    defaultPriceCurrency: 'coins',
  },
  'frame-emerald': {
    id: 'frame-emerald',
    category: 'frame',
    rarity: 'rare',
    nameKey: 'items.frame.emerald.name',
    descKey: 'items.frame.emerald.desc',
    assetUrl: '',
    colorValue: '#10b981',
    defaultPriceAmount: 3,
    defaultPriceCurrency: 'gems',
  },
  'frame-violet': {
    id: 'frame-violet',
    category: 'frame',
    rarity: 'epic',
    nameKey: 'items.frame.violet.name',
    descKey: 'items.frame.violet.desc',
    assetUrl: '',
    colorValue: '#a78bfa',
    defaultPriceAmount: 12,
    defaultPriceCurrency: 'gems',
  },
  'frame-prism': {
    id: 'frame-prism',
    category: 'frame',
    rarity: 'legendary',
    nameKey: 'items.frame.prism.name',
    descKey: 'items.frame.prism.desc',
    assetUrl: '',
    colorValue:
      'linear-gradient(135deg, #22d3ee 0%, #a78bfa 50%, #ec4899 100%)',
    defaultPriceAmount: 50,
    defaultPriceCurrency: 'gems',
  },
  'frame-gold': {
    id: 'frame-gold',
    category: 'frame',
    rarity: 'epic',
    nameKey: 'items.frame.gold.name',
    descKey: 'items.frame.gold.desc',
    assetUrl: '',
    colorValue: '#eab308',
    defaultPriceAmount: 15,
    defaultPriceCurrency: 'gems',
  },
  'frame-cyberpunk': {
    id: 'frame-cyberpunk',
    category: 'frame',
    rarity: 'legendary',
    nameKey: 'items.frame.cyberpunk.name',
    descKey: 'items.frame.cyberpunk.desc',
    assetUrl: '',
    colorValue:
      'linear-gradient(135deg, #ec4899 0%, #f43f5e 50%, #06b6d4 100%)',
    defaultPriceAmount: 48,
    defaultPriceCurrency: 'gems',
  },
  'frame-neon': {
    id: 'frame-neon',
    category: 'frame',
    rarity: 'legendary',
    nameKey: 'items.frame.neon.name',
    descKey: 'items.frame.neon.desc',
    assetUrl: '',
    colorValue: 'linear-gradient(135deg, #39ff14 0%, #00ffff 100%)',
    defaultPriceAmount: 45,
    defaultPriceCurrency: 'gems',
  },
  'frame-solar': {
    id: 'frame-solar',
    category: 'frame',
    rarity: 'epic',
    nameKey: 'items.frame.solar.name',
    descKey: 'items.frame.solar.desc',
    assetUrl: '',
    colorValue:
      'linear-gradient(135deg, #ff4500 0%, #ff8c00 50%, #ffd700 100%)',
    defaultPriceAmount: 18,
    defaultPriceCurrency: 'gems',
  },
  'frame-magma': {
    id: 'frame-magma',
    category: 'frame',
    rarity: 'epic',
    nameKey: 'items.frame.magma.name',
    descKey: 'items.frame.magma.desc',
    assetUrl: '',
    colorValue:
      'linear-gradient(135deg, #ff0000 0%, #ff4500 50%, #ff8c00 100%)',
    defaultPriceAmount: 22,
    defaultPriceCurrency: 'gems',
  },
  'frame-oceanic': {
    id: 'frame-oceanic',
    category: 'frame',
    rarity: 'epic',
    nameKey: 'items.frame.oceanic.name',
    descKey: 'items.frame.oceanic.desc',
    assetUrl: '',
    colorValue:
      'linear-gradient(135deg, #00ced1 0%, #1e90ff 50%, #0000ff 100%)',
    defaultPriceAmount: 22,
    defaultPriceCurrency: 'gems',
  },
  'frame-sakura': {
    id: 'frame-sakura',
    category: 'frame',
    rarity: 'epic',
    nameKey: 'items.frame.sakura.name',
    descKey: 'items.frame.sakura.desc',
    assetUrl: '',
    colorValue:
      'linear-gradient(135deg, #ffb7c5 0%, #ffc0cb 50%, #ff69b4 100%)',
    defaultPriceAmount: 20,
    defaultPriceCurrency: 'gems',
  },
  'frame-prismatic': {
    id: 'frame-prismatic',
    category: 'frame',
    rarity: 'legendary',
    nameKey: 'items.frame.prismatic.name',
    descKey: 'items.frame.prismatic.desc',
    assetUrl: '',
    colorValue:
      'linear-gradient(135deg, #ff00ff 0%, #00ffff 50%, #ffff00 100%)',
    defaultPriceAmount: 45,
    defaultPriceCurrency: 'gems',
  },
  'frame-void': {
    id: 'frame-void',
    category: 'frame',
    rarity: 'legendary',
    nameKey: 'items.frame.void.name',
    descKey: 'items.frame.void.desc',
    assetUrl: '',
    colorValue: 'linear-gradient(135deg, #000000 0%, #4b0082 100%)',
    defaultPriceAmount: 30,
    defaultPriceCurrency: 'gems',
  },
  'frame-supernova': {
    id: 'frame-supernova',
    category: 'frame',
    rarity: 'legendary',
    nameKey: 'items.frame.supernova.name',
    descKey: 'items.frame.supernova.desc',
    assetUrl: '',
    colorValue: 'linear-gradient(135deg, #ff007f 0%, #ffaa00 50%, #00ffff 100%)',
    defaultPriceAmount: 35,
    defaultPriceCurrency: 'gems',
  },
  'frame-synthwave': {
    id: 'frame-synthwave',
    category: 'frame',
    rarity: 'epic',
    nameKey: 'items.frame.synthwave.name',
    descKey: 'items.frame.synthwave.desc',
    assetUrl: '',
    colorValue: 'linear-gradient(135deg, #ff00a0 0%, #00ffff 100%)',
    defaultPriceAmount: 25,
    defaultPriceCurrency: 'gems',
  },
};
