import type { ShopItemDef } from './shop-types';

export const SHOP_BADGE_ITEMS: Record<string, ShopItemDef> = {
  'badge-newcomer': {
    id: 'badge-newcomer',
    category: 'badge',
    rarity: 'common',
    nameKey: 'items.badge.newcomer.name',
    descKey: 'items.badge.newcomer.desc',
    assetUrl: '/shop/badges/newcomer.png',
    defaultPriceAmount: 0,
    defaultPriceCurrency: 'coins',
    starter: true,
    purchasable: false,
  },
  'badge-scout': {
    id: 'badge-scout',
    category: 'badge',
    rarity: 'common',
    nameKey: 'items.badge.scout.name',
    descKey: 'items.badge.scout.desc',
    assetUrl: '/shop/badges/scout.png',
    defaultPriceAmount: 0,
    defaultPriceCurrency: 'coins',
    purchasable: false,
  },
  'badge-veteran': {
    id: 'badge-veteran',
    category: 'badge',
    rarity: 'common',
    nameKey: 'items.badge.veteran.name',
    descKey: 'items.badge.veteran.desc',
    assetUrl: '/shop/badges/veteran.png',
    defaultPriceAmount: 0,
    defaultPriceCurrency: 'coins',
    purchasable: false,
  },
  'badge-gladiator': {
    id: 'badge-gladiator',
    category: 'badge',
    rarity: 'rare',
    nameKey: 'items.badge.gladiator.name',
    descKey: 'items.badge.gladiator.desc',
    assetUrl: '/shop/badges/gladiator.png',
    defaultPriceAmount: 0,
    defaultPriceCurrency: 'coins',
    purchasable: false,
  },
  'badge-guardian': {
    id: 'badge-guardian',
    category: 'badge',
    rarity: 'rare',
    nameKey: 'items.badge.guardian.name',
    descKey: 'items.badge.guardian.desc',
    assetUrl: '/shop/badges/guardian.png',
    defaultPriceAmount: 0,
    defaultPriceCurrency: 'coins',
    purchasable: false,
  },
  'badge-champion': {
    id: 'badge-champion',
    category: 'badge',
    rarity: 'rare',
    nameKey: 'items.badge.champion.name',
    descKey: 'items.badge.champion.desc',
    assetUrl: '/shop/badges/champion.png',
    defaultPriceAmount: 0,
    defaultPriceCurrency: 'coins',
    purchasable: false,
  },
  'badge-conqueror': {
    id: 'badge-conqueror',
    category: 'badge',
    rarity: 'epic',
    nameKey: 'items.badge.conqueror.name',
    descKey: 'items.badge.conqueror.desc',
    assetUrl: '/shop/badges/conqueror.png',
    defaultPriceAmount: 0,
    defaultPriceCurrency: 'coins',
    purchasable: false,
  },
  'badge-warlord': {
    id: 'badge-warlord',
    category: 'badge',
    rarity: 'epic',
    nameKey: 'items.badge.warlord.name',
    descKey: 'items.badge.warlord.desc',
    assetUrl: '/shop/badges/warlord.png',
    defaultPriceAmount: 0,
    defaultPriceCurrency: 'coins',
    purchasable: false,
  },
  'badge-vanguard': {
    id: 'badge-vanguard',
    category: 'badge',
    rarity: 'epic',
    nameKey: 'items.badge.vanguard.name',
    descKey: 'items.badge.vanguard.desc',
    assetUrl: '/shop/badges/vanguard.png',
    defaultPriceAmount: 0,
    defaultPriceCurrency: 'coins',
    purchasable: false,
  },
  'badge-grandmaster': {
    id: 'badge-grandmaster',
    category: 'badge',
    rarity: 'epic',
    nameKey: 'items.badge.grandmaster.name',
    descKey: 'items.badge.grandmaster.desc',
    assetUrl: '/shop/badges/grandmaster.png',
    defaultPriceAmount: 0,
    defaultPriceCurrency: 'coins',
    purchasable: false,
  },
  'badge-ascendant': {
    id: 'badge-ascendant',
    category: 'badge',
    rarity: 'legendary',
    nameKey: 'items.badge.ascendant.name',
    descKey: 'items.badge.ascendant.desc',
    assetUrl: '/shop/badges/ascendant.png',
    defaultPriceAmount: 0,
    defaultPriceCurrency: 'coins',
    purchasable: false,
  },
  'badge-elite': {
    id: 'badge-elite',
    category: 'badge',
    rarity: 'legendary',
    nameKey: 'items.badge.elite.name',
    descKey: 'items.badge.elite.desc',
    assetUrl: '/shop/badges/elite.png',
    defaultPriceAmount: 0,
    defaultPriceCurrency: 'coins',
    purchasable: false,
  },
  'badge-sovereign': {
    id: 'badge-sovereign',
    category: 'badge',
    rarity: 'legendary',
    nameKey: 'items.badge.sovereign.name',
    descKey: 'items.badge.sovereign.desc',
    assetUrl: '/shop/badges/sovereign.png',
    defaultPriceAmount: 0,
    defaultPriceCurrency: 'coins',
    purchasable: false,
  },
  'badge-legend': {
    id: 'badge-legend',
    category: 'badge',
    rarity: 'legendary',
    nameKey: 'items.badge.legend.name',
    descKey: 'items.badge.legend.desc',
    assetUrl: '/shop/badges/legend.png',
    defaultPriceAmount: 0,
    defaultPriceCurrency: 'coins',
    purchasable: false,
  },
  'badge-nexus': {
    id: 'badge-nexus',
    category: 'badge',
    rarity: 'legendary',
    nameKey: 'items.badge.nexus.name',
    descKey: 'items.badge.nexus.desc',
    assetUrl: '/shop/badges/nexus.png',
    defaultPriceAmount: 0,
    defaultPriceCurrency: 'coins',
    purchasable: false,
  },
  'badge-paladin': {
    id: 'badge-paladin',
    category: 'badge',
    rarity: 'epic',
    nameKey: 'items.badge.paladin.name',
    descKey: 'items.badge.paladin.desc',
    assetUrl: '/shop/badges/paladin.png',
    defaultPriceAmount: 0,
    defaultPriceCurrency: 'coins',
    purchasable: false,
  },
  'badge-juggernaut': {
    id: 'badge-juggernaut',
    category: 'badge',
    rarity: 'epic',
    nameKey: 'items.badge.juggernaut.name',
    descKey: 'items.badge.juggernaut.desc',
    assetUrl: '/shop/badges/juggernaut.png',
    defaultPriceAmount: 0,
    defaultPriceCurrency: 'coins',
    purchasable: false,
  },
  'badge-paragon': {
    id: 'badge-paragon',
    category: 'badge',
    rarity: 'legendary',
    nameKey: 'items.badge.paragon.name',
    descKey: 'items.badge.paragon.desc',
    assetUrl: '/shop/badges/paragon.png',
    defaultPriceAmount: 0,
    defaultPriceCurrency: 'coins',
    purchasable: false,
  },
  'badge-titan': {
    id: 'badge-titan',
    category: 'badge',
    rarity: 'legendary',
    nameKey: 'items.badge.titan.name',
    descKey: 'items.badge.titan.desc',
    assetUrl: '/shop/badges/titan.png',
    defaultPriceAmount: 0,
    defaultPriceCurrency: 'coins',
    purchasable: false,
  },
  'badge-archon': {
    id: 'badge-archon',
    category: 'badge',
    rarity: 'legendary',
    nameKey: 'items.badge.archon.name',
    descKey: 'items.badge.archon.desc',
    assetUrl: '/shop/badges/archon.png',
    defaultPriceAmount: 0,
    defaultPriceCurrency: 'coins',
    purchasable: false,
  },
  'badge-mythic': {
    id: 'badge-mythic',
    category: 'badge',
    rarity: 'legendary',
    nameKey: 'items.badge.mythic.name',
    descKey: 'items.badge.mythic.desc',
    assetUrl: '/shop/badges/mythic.png',
    defaultPriceAmount: 0,
    defaultPriceCurrency: 'coins',
    purchasable: false,
  },
};
