import type { ShopItemDef } from './shop-types';

export const BANNERS: Record<string, ShopItemDef> = {
  'banner-default': {
    id: 'banner-default',
    category: 'banner',
    rarity: 'common',
    nameKey: 'items.banner.default.name',
    descKey: 'items.banner.default.desc',
    assetUrl: '',
    colorValue: '#0f172a',
    defaultPriceAmount: 0,
    defaultPriceCurrency: 'coins',
    starter: true,
  },
  'banner-slate': {
    id: 'banner-slate',
    category: 'banner',
    rarity: 'common',
    nameKey: 'items.banner.slate.name',
    descKey: 'items.banner.slate.desc',
    assetUrl: '',
    colorValue: 'linear-gradient(135deg, #1e293b 0%, #334155 100%)',
    defaultPriceAmount: 250,
    defaultPriceCurrency: 'coins',
  },
  'banner-tide': {
    id: 'banner-tide',
    category: 'banner',
    rarity: 'rare',
    nameKey: 'items.banner.tide.name',
    descKey: 'items.banner.tide.desc',
    assetUrl: '',
    colorValue: 'linear-gradient(135deg, #0ea5e9 0%, #14b8a6 100%)',
    defaultPriceAmount: 3,
    defaultPriceCurrency: 'gems',
  },
  'banner-twilight': {
    id: 'banner-twilight',
    category: 'banner',
    rarity: 'epic',
    nameKey: 'items.banner.twilight.name',
    descKey: 'items.banner.twilight.desc',
    assetUrl: '',
    colorValue: 'linear-gradient(135deg, #6366f1 0%, #ec4899 100%)',
    defaultPriceAmount: 12,
    defaultPriceCurrency: 'gems',
  },
  'banner-nebula': {
    id: 'banner-nebula',
    category: 'banner',
    rarity: 'legendary',
    nameKey: 'items.banner.nebula.name',
    descKey: 'items.banner.nebula.desc',
    assetUrl: '',
    colorValue:
      'linear-gradient(135deg, #1e1b4b 0%, #6366f1 35%, #ec4899 70%, #f59e0b 100%)',
    defaultPriceAmount: 45,
    defaultPriceCurrency: 'gems',
  },
  'banner-cyberpunk': {
    id: 'banner-cyberpunk',
    category: 'banner',
    rarity: 'epic',
    nameKey: 'items.banner.cyberpunk.name',
    descKey: 'items.banner.cyberpunk.desc',
    assetUrl: '',
    colorValue:
      'linear-gradient(135deg, #0f172a 0%, #f43f5e 50%, #eab308 100%)',
    defaultPriceAmount: 15,
    defaultPriceCurrency: 'gems',
  },
  'banner-void': {
    id: 'banner-void',
    category: 'banner',
    rarity: 'legendary',
    nameKey: 'items.banner.void.name',
    descKey: 'items.banner.void.desc',
    assetUrl: '',
    colorValue:
      'linear-gradient(135deg, #030712 0%, #111827 50%, #312e81 100%)',
    defaultPriceAmount: 40,
    defaultPriceCurrency: 'gems',
  },
  'banner-magma': {
    id: 'banner-magma',
    category: 'banner',
    rarity: 'epic',
    nameKey: 'items.banner.magma.name',
    descKey: 'items.banner.magma.desc',
    assetUrl: '',
    colorValue: 'linear-gradient(135deg, #7f1d1d 0%, #f97316 100%)',
    defaultPriceAmount: 25,
    defaultPriceCurrency: 'gems',
  },
  'banner-sakura': {
    id: 'banner-sakura',
    category: 'banner',
    rarity: 'epic',
    nameKey: 'items.banner.sakura.name',
    descKey: 'items.banner.sakura.desc',
    assetUrl: '',
    colorValue: 'linear-gradient(135deg, #fda4af 0%, #f472b6 100%)',
    defaultPriceAmount: 25,
    defaultPriceCurrency: 'gems',
  },
  'banner-solar': {
    id: 'banner-solar',
    category: 'banner',
    rarity: 'epic',
    nameKey: 'items.banner.solar.name',
    descKey: 'items.banner.solar.desc',
    assetUrl: '',
    colorValue: 'linear-gradient(135deg, #fbbf24 0%, #ea580c 100%)',
    defaultPriceAmount: 25,
    defaultPriceCurrency: 'gems',
  },
  'banner-neon': {
    id: 'banner-neon',
    category: 'banner',
    rarity: 'epic',
    nameKey: 'items.banner.neon.name',
    descKey: 'items.banner.neon.desc',
    assetUrl: '',
    colorValue: 'linear-gradient(135deg, #22c55e 0%, #06b6d4 100%)',
    defaultPriceAmount: 25,
    defaultPriceCurrency: 'gems',
  },
  'banner-oceanic': {
    id: 'banner-oceanic',
    category: 'banner',
    rarity: 'epic',
    nameKey: 'items.banner.oceanic.name',
    descKey: 'items.banner.oceanic.desc',
    assetUrl: '',
    colorValue:
      'linear-gradient(135deg, #0284c7 0%, #0369a1 50%, #1e3a8a 100%)',
    defaultPriceAmount: 25,
    defaultPriceCurrency: 'gems',
  },
  'banner-prismatic': {
    id: 'banner-prismatic',
    category: 'banner',
    rarity: 'legendary',
    nameKey: 'items.banner.prismatic.name',
    descKey: 'items.banner.prismatic.desc',
    assetUrl: '',
    colorValue:
      'linear-gradient(135deg, #ec4899 0%, #8b5cf6 50%, #06b6d4 100%)',
    defaultPriceAmount: 40,
    defaultPriceCurrency: 'gems',
  },
  'banner-supernova': {
    id: 'banner-supernova',
    category: 'banner',
    rarity: 'legendary',
    nameKey: 'items.banner.supernova.name',
    descKey: 'items.banner.supernova.desc',
    assetUrl: '',
    colorValue: 'linear-gradient(135deg, #ff007f 0%, #ffaa00 50%, #00ffff 100%)',
    defaultPriceAmount: 30,
    defaultPriceCurrency: 'gems',
  },
  'banner-synthwave': {
    id: 'banner-synthwave',
    category: 'banner',
    rarity: 'epic',
    nameKey: 'items.banner.synthwave.name',
    descKey: 'items.banner.synthwave.desc',
    assetUrl: '',
    colorValue: 'linear-gradient(135deg, #2e0854 0%, #ff00a0 50%, #00ffff 100%)',
    defaultPriceAmount: 25,
    defaultPriceCurrency: 'gems',
  },
};
