import type { GameMetadata, BaseGameWidgetProps } from './types';
import type { GameSlug } from './registry.types';

export { GameSlug };

export const gameLoaders: Record<
  string,
  () => Promise<{ default: React.ComponentType<BaseGameWidgetProps> }>
> = {
  critical_v1: () => import('@/widgets/CardGames/CriticalGame'),
  sea_battle_v1: () => import('@/widgets/StrategyGames/SeaBattleGame'),
  glimworm_v1: () => import('@/widgets/ActionGames/GlimwormGame'),
  tic_tac_toe_v1: () => import('@/widgets/BoardGames/TicTacToeGame'),
  cascade_v1: () => import('@/widgets/CardGames/CascadeGame'),
  chess_v1: () => import('@/widgets/BoardGames/ChessGame'),
  checkers_v1: () => import('@/widgets/BoardGames/CheckersGame'),
  cat_dash_v1: () => import('@/widgets/ActionGames/CatDashGame'),
  backgammon_v1: () => import('@/widgets/BoardGames/BackgammonGame'),
  hearts_v1: () => import('@/widgets/CardGames/HeartsGame'),
  spades_v1: () => import('@/widgets/CardGames/SpadesGame'),
  go_v1: () => import('@/widgets/BoardGames/GoGame'),
  pachisi_v1: () => import('@/widgets/BoardGames/PachisiGame'),
  // Add more games as they are implemented
} as const;

// Game metadata registry
export const gameMetadata: Partial<Record<GameSlug, GameMetadata>> = {
  critical_v1: {
    slug: 'critical_v1',
    name: 'Critical',
    description: 'A high-stakes version of Russian Roulette',
    category: 'Card Game',
    minPlayers: 2,
    maxPlayers: 5,
    estimatedDuration: 15,
    complexity: 2,
    ageRating: 'PG-13',
    thumbnail: '/games/critical.jpg',
    version: '1.0.0',
    supportsAI: true,
    tags: ['cards', 'party', 'fun', 'strategy'],
    implementationPath: '@/widgets/CardGames/CriticalGame',
    lastUpdated: '2024-01-01',
    status: 'active',
  },
  texas_holdem_v1: {
    slug: 'texas_holdem_v1',
    name: "Texas Hold'em Poker",
    description: "Classic poker game with Texas Hold'em rules",
    category: 'Card Game',
    minPlayers: 2,
    maxPlayers: 9,
    estimatedDuration: 60,
    complexity: 4,
    ageRating: 'PG-16',
    thumbnail: '/games/texas-holdem.jpg',
    version: '1.0.0',
    supportsAI: true,
    tags: ['cards', 'poker', 'strategy', 'betting'],
    implementationPath: '@/widgets/TexasHoldemGame',
    lastUpdated: '2024-01-01',
    status: 'active',
  },
  glimworm_v1: {
    slug: 'glimworm_v1',
    name: 'Glimworm',
    description: 'A glow-in-the-dark snake battle for 2–10 players.',
    category: 'Action',
    minPlayers: 2,
    maxPlayers: 10,
    estimatedDuration: 5,
    complexity: 1,
    ageRating: 'G',
    thumbnail: '/games/glimworm.svg',
    version: '1.0.0',
    supportsAI: true,
    tags: ['action', 'arena', 'real-time', 'snake', 'casual'],
    implementationPath: '@/widgets/ActionGames/GlimwormGame',
    lastUpdated: '2026-05-02',
    status: 'beta',
  },
  sea_battle_v1: {
    slug: 'sea_battle_v1',
    name: 'Sea Battle',
    description: 'Classic naval combat game for up to 6 players',
    category: 'Strategy',
    minPlayers: 2,
    maxPlayers: 4,
    estimatedDuration: 20,
    complexity: 2,
    ageRating: 'PG',
    thumbnail: '/games/sea-battle.jpg',
    version: '1.0.0',
    supportsAI: true,
    tags: ['strategy', 'classic', 'naval'],
    implementationPath: '@/widgets/StrategyGames/SeaBattleGame',
    lastUpdated: '2024-01-30',
    status: 'beta',
  },
  // Sample metadata for other games (can be expanded)
  chess_v1: {
    slug: 'chess_v1',
    name: 'Chess',
    description: 'The classic strategy board game',
    category: 'Board Game',
    minPlayers: 2,
    maxPlayers: 2,
    estimatedDuration: 30,
    complexity: 5,
    ageRating: 'G',
    thumbnail: '/games/chess.jpg',
    version: '1.0.0',
    supportsAI: true,
    tags: ['board', 'strategy', 'classic'],
    implementationPath: '@/widgets/BoardGames/ChessGame',
    lastUpdated: '2024-01-01',
    status: 'experimental',
  },
  checkers_v1: {
    slug: 'checkers_v1',
    name: 'Checkers',
    description: 'Classic board game of strategic piece movement',
    category: 'Board Game',
    minPlayers: 2,
    maxPlayers: 2,
    estimatedDuration: 20,
    complexity: 3,
    ageRating: 'G',
    thumbnail: '/games/checkers.jpg',
    version: '1.0.0',
    supportsAI: true,
    tags: ['board', 'strategy', 'classic'],
    implementationPath: '@/widgets/BoardGames/CheckersGame',
    lastUpdated: '2024-01-01',
    status: 'experimental',
  },
  cascade_v1: {
    slug: 'cascade_v1',
    name: 'Cascade',
    description:
      'Shedding card game in the Crazy Eights family with stacking penalties and four selectable themes',
    category: 'Card Game',
    minPlayers: 2,
    maxPlayers: 10,
    estimatedDuration: 10,
    complexity: 2,
    ageRating: 'G',
    thumbnail: '/games/cascade.jpg',
    version: '1.0.0',
    supportsAI: true,
    tags: ['cards', 'casual', 'family', 'matching', 'classic'],
    implementationPath: '@/widgets/CardGames/CascadeGame',
    lastUpdated: '2026-05-26',
    status: 'beta',
  },
  tic_tac_toe_v1: {
    slug: 'tic_tac_toe_v1',
    name: 'Tic-Tac-Toe',
    description: 'Classic 3-in-a-row with themed variants and 3×3 – 9×9 boards',
    category: 'Board Game',
    minPlayers: 2,
    maxPlayers: 5,
    estimatedDuration: 5,
    complexity: 1,
    ageRating: 'G',
    thumbnail: '/games/tic-tac-toe.jpg',
    version: '1.0.0',
    supportsAI: true,
    tags: ['board', 'classic', 'casual', 'quick', 'strategy'],
    implementationPath: '@/widgets/BoardGames/TicTacToeGame',
    lastUpdated: '2026-05-26',
    status: 'beta',
  },
  the_heist_v1: {
    slug: 'the_heist_v1',
    name: 'The Heist',
    description:
      'A cooperative heist-themed card game of cunning and deception',
    category: 'Card Game',
    minPlayers: 3,
    maxPlayers: 6,
    estimatedDuration: 30,
    complexity: 3,
    ageRating: 'PG-13',
    thumbnail: '/games/the-heist.jpg',
    version: '1.0.0',
    supportsAI: false,
    tags: ['cards', 'cooperative', 'heist', 'deception'],
    implementationPath: '@/widgets/TheHeistGame',
    lastUpdated: '2026-02-20',
    status: 'coming_soon',
  },
  the_cursed_banquet_v1: {
    slug: 'the_cursed_banquet_v1',
    name: 'The Cursed Banquet',
    description: 'A dark mystery dinner party card game with hidden roles',
    category: 'Card Game',
    minPlayers: 4,
    maxPlayers: 8,
    estimatedDuration: 45,
    complexity: 4,
    ageRating: 'PG-16',
    thumbnail: '/games/the-cursed-banquet.jpg',
    version: '1.0.0',
    supportsAI: false,
    tags: ['cards', 'mystery', 'hidden-roles', 'party'],
    implementationPath: '@/widgets/TheCursedBanquetGame',
    lastUpdated: '2026-02-20',
    status: 'coming_soon',
  },
  cat_dash_v1: {
    slug: 'cat_dash_v1',
    name: 'Cat Dash',
    description: 'A cat racing dice game with unique abilities and themes',
    category: 'Race',
    minPlayers: 2,
    maxPlayers: 6,
    estimatedDuration: 15,
    complexity: 1,
    ageRating: 'PG',
    thumbnail: '/games/cat-dash.jpg',
    version: '1.0.0',
    supportsAI: true,
    tags: ['cats', 'race', 'dice', 'family', 'fun'],
    implementationPath: '@/widgets/ActionGames/CatDashGame',
    lastUpdated: '2026-07-23',
    status: 'coming_soon',
  },
  backgammon_v1: {
    slug: 'backgammon_v1',
    name: 'Backgammon',
    description:
      'Classic 24-point board game with dice rolls, bearing off, and AI bot opponents',
    category: 'Board Game',
    minPlayers: 2,
    maxPlayers: 2,
    estimatedDuration: 20,
    complexity: 3,
    ageRating: 'PG',
    thumbnail: '/games/backgammon.jpg',
    version: '1.0.0',
    supportsAI: true,
    tags: ['backgammon', 'dice', 'board', 'classic', 'strategy'],
    implementationPath: '@/widgets/BoardGames/BackgammonGame',
    lastUpdated: '2026-08-21',
    status: 'active',
  },
  hearts_v1: {
    slug: 'hearts_v1',
    name: 'Hearts',
    description:
      'Classic 4-player trick-taking card game — avoid penalty cards and shoot the moon',
    category: 'Card Game',
    minPlayers: 4,
    maxPlayers: 4,
    estimatedDuration: 30,
    complexity: 3,
    ageRating: 'G',
    thumbnail: '/games/hearts.jpg',
    version: '1.0.0',
    supportsAI: true,
    tags: ['cards', 'trick-taking', 'classic', 'strategy'],
    implementationPath: '@/widgets/CardGames/HeartsGame',
    lastUpdated: '2026-08-22',
    status: 'beta',
  },
  spades_v1: {
    slug: 'spades_v1',
    name: 'Spades',
    description:
      'Classic 4-player partnership card game — bid your tricks and let spades trump',
    category: 'Card Game',
    minPlayers: 4,
    maxPlayers: 4,
    estimatedDuration: 35,
    complexity: 3,
    ageRating: 'G',
    thumbnail: '/games/spades.jpg',
    version: '1.0.0',
    supportsAI: true,
    tags: ['cards', 'trick-taking', 'partnership', 'bidding', 'classic'],
    implementationPath: '@/widgets/CardGames/SpadesGame',
    lastUpdated: '2026-08-23',
    status: 'beta',
  },
  go_v1: {
    slug: 'go_v1',
    name: 'Go',
    description:
      'Classic Go on 9×9, 13×13 and 19×19 boards — captures, ko rule, area scoring, and AI opponents',
    category: 'Board Game',
    minPlayers: 2,
    maxPlayers: 2,
    estimatedDuration: 25,
    complexity: 5,
    ageRating: 'G',
    thumbnail: '/games/go.jpg',
    version: '1.0.0',
    supportsAI: true,
    tags: ['go', 'baduk', 'weiqi', 'board', 'classic', 'strategy'],
    implementationPath: '@/widgets/BoardGames/GoGame',
    lastUpdated: '2026-08-23',
    status: 'beta',
  },
  pachisi_v1: {
    slug: 'pachisi_v1',
    name: 'Pachisi',
    description:
      'Classic cross-and-circle race game for 2–4 players — roll a six, capture rivals, and bring all tokens home',
    category: 'Board Game',
    minPlayers: 2,
    maxPlayers: 4,
    estimatedDuration: 15,
    complexity: 1,
    ageRating: 'G',
    thumbnail: '/games/pachisi.svg',
    version: '1.0.0',
    supportsAI: true,
    tags: ['pachisi', 'ludo', 'dice', 'board', 'race', 'family'],
    implementationPath: '@/widgets/BoardGames/PachisiGame',
    lastUpdated: '2026-08-23',
    status: 'beta',
  },
  solitaire_v1: {
    slug: 'solitaire_v1',
    name: 'Solitaire',
    description:
      'Classic Klondike Solitaire — single-player card puzzle that runs entirely in your browser',
    category: 'Card Game',
    minPlayers: 1,
    maxPlayers: 1,
    estimatedDuration: 10,
    complexity: 1,
    ageRating: 'G',
    thumbnail: '/games/solitaire.svg',
    version: '1.0.0',
    supportsAI: false,
    tags: ['solitaire', 'klondike', 'cards', 'single-player', 'classic'],
    implementationPath: '@/widgets/PuzzleGames/SolitaireGame',
    lastUpdated: '2026-08-24',
    status: 'beta',
  },
  minesweeper_v1: {
    slug: 'minesweeper_v1',
    name: 'Minesweeper',
    description:
      'Classic Minesweeper — clear beginner to expert grids without detonating a single mine, entirely in your browser',
    category: 'Puzzle',
    minPlayers: 1,
    maxPlayers: 1,
    estimatedDuration: 5,
    complexity: 2,
    ageRating: 'G',
    thumbnail: '/games/minesweeper.svg',
    version: '1.0.0',
    supportsAI: false,
    tags: ['minesweeper', 'puzzle', 'logic', 'single-player', 'classic'],
    implementationPath: '@/widgets/PuzzleGames/MinesweeperGame',
    lastUpdated: '2026-08-24',
    status: 'beta',
  },
  sudoku_v1: {
    slug: 'sudoku_v1',
    name: 'Sudoku',
    description:
      'Classic Sudoku with unique-solution puzzles on easy, medium, and hard grids — pencil marks included',
    category: 'Puzzle',
    minPlayers: 1,
    maxPlayers: 1,
    estimatedDuration: 15,
    complexity: 2,
    ageRating: 'G',
    thumbnail: '/games/sudoku.svg',
    version: '1.0.0',
    supportsAI: false,
    tags: ['sudoku', 'numbers', 'puzzle', 'logic', 'single-player', 'classic'],
    implementationPath: '@/widgets/PuzzleGames/SudokuGame',
    lastUpdated: '2026-08-24',
    status: 'beta',
  },
  game_2048_v1: {
    slug: 'game_2048_v1',
    name: '2048',
    description:
      'The addictive tile-merging puzzle — slide and merge equal tiles across a 4×4 grid to reach 2048',
    category: 'Puzzle',
    minPlayers: 1,
    maxPlayers: 1,
    estimatedDuration: 10,
    complexity: 1,
    ageRating: 'G',
    thumbnail: '/games/2048.svg',
    version: '1.0.0',
    supportsAI: false,
    tags: ['2048', 'tiles', 'merge', 'puzzle', 'single-player', 'casual'],
    implementationPath: '@/widgets/PuzzleGames/Game2048',
    lastUpdated: '2026-08-24',
    status: 'beta',
  },
};

/**
 * i18n key for a category label. Unknown categories fall back to the raw
 * string by returning `undefined` — callers must handle that.
 */
export const CATEGORY_LABEL_KEYS: Record<string, string> = {
  'Card Game': 'games.shared.category.cardGame',
  'Board Game': 'games.shared.category.boardGame',
  Action: 'games.shared.category.action',
  Strategy: 'games.shared.category.strategy',
  Race: 'games.shared.category.race',
  Puzzle: 'games.shared.category.puzzle',
};

export function getCategoryLabelKey(category: string): string | undefined {
  return CATEGORY_LABEL_KEYS[category];
}

/**
 * Preferred tab order for catalog categories. New categories not listed here
 * are appended after these, in first-seen order, so adding a game to
 * `gameMetadata` is the only registration step needed.
 */
const CATEGORY_ORDER = [
  'Card Game',
  'Board Game',
  'Strategy',
  'Action',
  'Puzzle',
] as const;

/**
 * Derives the catalog category tabs from `gameMetadata`. A new game only
 * needs an entry in `gameMetadata` (+ `gameLoaders`) — its category appears
 * here automatically. Coming-soon/deprecated games are excluded so their
 * genre does not create empty tabs.
 */
export function getVisibleGameCategories(): string[] {
  const seen = new Set<string>();
  for (const order of CATEGORY_ORDER) seen.add(order);
  for (const meta of Object.values(gameMetadata)) {
    if (meta.status === 'coming_soon' || meta.status === 'deprecated') continue;
    seen.add(meta.category);
  }
  return Array.from(seen);
}
