name: Dependency Review

permissions: read-all

on:
  pull_request:
    branches: [main, develop]

jobs:
  dependency-review:
    name: Check for vulnerable dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v7

      - name: Dependency Review
        uses: actions/dependency-review-action@v5
        continue-on-error: true
        with:
          fail-on-severity: moderate
          comment-summary-in-pr: always
          deny-licenses: GPL-3.0, AGPL-3.0
